package fr.ozf.fmr;

import java.util.Random;

public class fmrBlague
{
   private String blg;
   private static final fmrBlague blague[] =
   {
      new fmrBlague("Pourquoi faut-il se méfier des sirènes au volant ?\nParce qu'elles font des queues de poisson !"),
      new fmrBlague("Pourquoi n'y a t il pas de corbeilles dans les piscines ?\nParce que la corbeille a papier."),
      new fmrBlague("Qu'est-ce qu'un squelette dans une armoire ?\nC'est quelqu'un qui a gagné à cache-cache."),
      new fmrBlague("Qu'est-ce qui fait 999 fois Tic et 1 fois Toc ?\nUn mille pattes avec une jambe de bois !"),
      new fmrBlague("Quelle est la ressemblance entre un parachute et l'humour ?\nQuand on n'en a pas, on s'écrase !"),
      new fmrBlague("Quelle est la ressemblance entre un facteur et un jongleur ?\nIl leur faut tous les deux beaucoup d'adresse."),
      new fmrBlague("Quelle différence y a-t-il entre un horloger et une girouette ?\nL'horloger vend des montres et la girouette montre le vent."),
      new fmrBlague("Quel est le sport le plus fruité ?\nLa boxe, parce que quand on te met une pêche dans la poire, tu tombes dans les pommes, t'as pas intérêt à ramener ta fraise et tout ça pour des prunes."),
      new fmrBlague("Quel est le plus beau compliment qu'un cannibale puisse faire à une fille ?\nVous êtes belle à croquer !"),
      new fmrBlague("Un e parle avec un é.\n- Tu peux répéter, je ne comprends rien avec ton accent !"),
      new fmrBlague("Merlin rencontre Arthur pour la première fois.\nArthur regarde le vieillard et lui dit : Enchanté ! \nL'autre répond : Non non, Enchanteur !"),
      new fmrBlague("Dans la rue, un homme demande à une vieille dame :\n- Vous n'auriez pas vu un policier ?\n- Non.\n- Alors donnez-moi votre sac à main !"),
      new fmrBlague("Dans un frigo, un oeuf aperçoit un kiwi à coté de lui.\n- Tiens, il est périmé celui-là !"),
      new fmrBlague("- T'as vu mon fer à repasser ?\n- T'inquiète il va repasser !"),
      new fmrBlague("2 cosmonautes discutent :\n- Tu crois qu'on peut se cogner contre quelqu'un en apesanteur ?\n- Oui, mais ce sont toujours des accidents sans gravité !"),
      new fmrBlague("2 escarpins discutent à un défilé de mode :\n- Tu penses que je suis à la hauteur ?\n- Mais oui, tu as un talon fou !"),
      new fmrBlague("2 vampires discutent :\n- Tu veux un peu d'hémoglobine ?\n- Non merci, je suis au régime\n- Tu peux y aller, c'est du zéro pour sang !"),
      new fmrBlague("- Tu connais l'histoire de la feuille de papier ?\n- Non.\n- Elle déchire !"),
      new fmrBlague("2 icebergs discutent :\n- Alors il paraît que ta femme à accouché ?\n- Oui, on a eu un beau petit glaçon !"),
      new fmrBlague("- Docteur, je ne sais plus ce que je dis !\n- Et vous avez ce problème depuis quand ?\n- Quel problème ?"),
      new fmrBlague("Une grand-mère demande à son petit fils :\n- Qu'est-ce que ça veut dire « zarbi » ?\n- La même chose que « chelou » mamie"),
      new fmrBlague("Une mère demande à son fils :\n- Tu as fais ta lettre au Père Noël ?\n- Non mais je lui ai envoyé un texto !"),
      new fmrBlague("Une mandarine va rendre visite à une clémentine malade :\n- Alors, que t'arrive-t-il ?\n- Que des pépins !"),
      new fmrBlague("Deux téléphones portables sont à la plage. Soudain l'un d'eux se met à grelotter... \n- Tu n'as quand même pas froid, il fait 30 degrés !\n- Mais non, je reçois un texto !"),
      new fmrBlague("Deux nuages discutent :\n- On va encore mal dormir, ils construisent de nouveaux gratte-ciel !"),
      new fmrBlague("A la douane :\n- Qu'est ce que vous transportez ?\n- 6000 huîtres\n- Ouvrez les toutes."),
      new fmrBlague("Deux petits garçons discutent :\n- Moi j'adore la barbe à papa !\n- Le mien il se rase tous les matins."),
      new fmrBlague("- Oh regarde un mouche !\n- Non, pas un mouche, une mouche !\n- Ben ça alors tu as de bons yeux."),
      new fmrBlague("- Bonjour, je voudrais un livre !\n- De quel auteur ?\n- Pas trop grand, je n'ai pas beaucoup de place."),
      new fmrBlague("Deux enfants discutent :\n- Tu as quel âge ?\n- Attends je vais regarder l'étiquette de mon slip !"),
      new fmrBlague("Chez le coiffeur :\n- Tu veux du gel dans tes cheveux ?\n- Non merci j'ai déjà froid"),
      new fmrBlague("Maman tu peux me faire une queue de cheval ?\n- Ils sont trop courts !\n- Et bien fais-moi une queue de poney alors !"),
      new fmrBlague("Dans un magasin :\n- Je peux essayer ce pantalon en vitrine ?\n- Vous ne préférez pas l'essayer en cabine ?"),
      new fmrBlague("Deux bombes discutent :\n- Rendez-vous à 5 heures pétantes !"),
      new fmrBlague("2 explosifs se rencontrent :\nAlors, ça boom ?"),
      new fmrBlague("Deux orages discutent :\n- Tu t'es éclaté hier ?\n- C'était du tonnerre !"),
      new fmrBlague("Deux tee-shirts discutent :\n- Ca caille ici on se croirait au pull nord !"),
      new fmrBlague("Deux chaussettes se croisent :\n- Ça va ?\n- Et toi ? Comment tu te sens ?"),
      new fmrBlague("Deux petits pois discutent :\n- T'étais où hier ? On t'a pas vu en boîte !"),
      new fmrBlague("Deux pantoufles se rencontrent :\n- Salut, savate ?\n- Ouais, c'est le pied !"),
      new fmrBlague("Deux coiffeurs discutent :\n- Tu veux bien m'aider pour une coupe ?\n- Tu peux te brosser !"),
      new fmrBlague("Elle réfléchit avant de sortir avec moi\n- Et alors ?\n- Ça fait deux ans?"),
      new fmrBlague("- Tu m'offres une bague ?\n- Pourquoi faire ? T'en as déjà plein les dents !"),
      new fmrBlague("Deux vampires discutent :\n- Tu l'aimes ?\n- Je suis complètement mordu !"),
      new fmrBlague("Une vis à un tournevis :\n- Tu me fais tourner la tête"),
      new fmrBlague("Deux gendarmes :\n- C'est quoi ton secret ?\n- Une crème qui fait la peau-lisse"),
      new fmrBlague("Qu'est ce qu'une catapulte à salade ?\nUn lance roquette."),
      new fmrBlague("Quel fruit obtient-on en tirant sur la queue d'une vache ?\nUn meuhh-long"),
      new fmrBlague("Deux pianos se croisent :\n- Ça va, toi ?\n- Bof, j'ai mal au do."),
      new fmrBlague("Que fait un sportif à qui on étire le nez ?\nIl prend son nez-long !"),
      new fmrBlague("Quel est le fruit le plus végétarien ?\nLa pas steak!"),
      new fmrBlague("Deux obus discutent :\n- T'as vu ma nouvelle fiancée ?\n- Ouais : c'est une vraie bombe !"),
      new fmrBlague("Une toute petite fille sort de la salle de bain. Elle crie : \n- Maman, maman, est-ce que tu savais que papa est un garçon ?"),
      new fmrBlague("Une mère dit à son garçon : \n-N'oublie pas que nous sommes sur terre pour travailler. \n- Bon, alors moi, plus tard je serai marin !"),
      new fmrBlague("Une jeune fille se plaint à son amie : \n- A tous nos rendez-vous, il m'offre des fleurs fanées. \n- Eh bien, essaye d'arriver à l'heure ..."),
      new fmrBlague("Une jeune femme demande à une autre : \n- Alors, toujours amoureuse de ton parachutiste ? \n- Non, je l'ai laissé tombé."),
      new fmrBlague("Une dame dit à un oculiste : \n- Docteur, ma vue baisse. \n- Ah ! fait l'oculiste, et que faites-vous dans la vies ? \n- ben justement, je suis voyante !"),
      new fmrBlague("Un vendeur de journaux clame le titre de son quotidien: \nScandale! 60 personnes se sont fait escroquer.\nUn passant achète le journal. Alors le vendeur dit: \nScandale! 61 personnes se sont fait escroquer."),
      new fmrBlague("Un touriste visite un château en Ecosse: \n- On m'a dit que votre château est hanté, dit-il au châtelain. \n- C'est faux! Je n'y ai jamais vu aucun fantôme et pourtant je vis ici depuis 300 ans."),
      new fmrBlague("Un star de cinéma est en train de prendre son bain. le robinet d'eau froide dit au robinet d'eau chaude\nAlors, toi aussi, elle te fais tourner la tête ?"),
      new fmrBlague("Un prêtre un peu fou monte un escalier en chantonnant: \nC'est l'abbé bête qui monte qui monte qui monte..."),
      new fmrBlague("Un paresseux sourd se promène dans la rue. Tout à coup, il dit:\nSi je m'écoutais, j'irai au bureau."),
      new fmrBlague("Un monsieur demande au serveur :\n- Est-ce que je pourrais avoir un verre de vin ?\n- Du blanc ou du rouge ? \n- Ça n'a pas d'importance, c'est pour un aveugle."),
      new fmrBlague("Un invité murmure à sa voisine: \n- Le champagne vous rend jolie.\n- Je n'en ai pas bu une seule coupe. \n- Oui, mais moi j'en suis à ma dixième!"),
      new fmrBlague("Un hommes dit à un ami :\n- Salut, je me suis évadé de prison !\n- Pas possible ! Coment as-tu fait ?\n- Facile, j'ai profité d'une journée porte ouverte."),
      new fmrBlague("Un homme va acheter un lit et demande à ce qu'il soit très solide. Le vendeur s'étonne: \n- Pourtant, vous n'êtes pas si gros. \n- Non, mais j'ai le sommeil lourd!"),
      new fmrBlague("Un homme se présente chez le médecin: \n- Voi-voilà-doc-docteur, je bébé, je bégaie. Alors le médecin: \n- Bien, nous zazaa, nous zalons a-a-arran, arranger ça!"),
      new fmrBlague("Un homme raconte : \n- Je suis parti en voyage. J'ai écrit tous les jours à ma fiancée et à mon retour, elle s'est mariée. \n- Eh bien, bravo ! \n- Non, sniff, elle s'est mariée avec le facteur !"),
      new fmrBlague("Un homme dit à un autre: \n- On joue aux dames? \n- Je ne peux pas, je ne suis pas marié!"),
      new fmrBlague("Un gendarme fait stopper une automobiliste : \n- Vous n'avez pas vu le feu rouge ? \n- Si si. C'est vous que je n'avais pas vu !"),
      new fmrBlague("Un gendarme arrête une automobile qui roulait à trop grande vitesse : \n- A combien rouliez-vous ? \n- A deux seulement ! Mais si vous voulez monter, il reste de la place !"),
      new fmrBlague("Un cuisinier dit au serveur: \n- Supprime le cassoulet maison sur les menus. Je viens de casser l'ouvre-boîtes."),
      new fmrBlague("Un copain dit à Julien : \n- Tu m'avais donné ta parole, et tu ne l'as pas tenue. \n- je ne pouvais pas la tenir puisque je te l'avais donnée."),
      new fmrBlague("Un commerçant demande à un client: \n- Qu'est-ce que je vous sers? \n- Serrez-moi la main!"),
      new fmrBlague("Un clochard discute avec un autre : \n- Grâce à ma trompette, je suis très riche. \n- Les gens te donnent beaucoup d'argent pour que tu joues ? \n- Non justement, pour que je ne joue pas."),
      new fmrBlague("Un client entre chez un marchand de tableaux. Il demande: \n- Je voudrais quelque chose pour ma salle-à-manger. Il faut que ce soit de bon goût, pas trop cher, et de préférence, à l'huile. \n- Je vois, répond le marchand. Vous voulez une boite de sardines."),
      new fmrBlague("Un casse-pieds demande à un peintre: \n- Pourquoi ne peignez-vous que des paysages? \n- Parce que jamais un arbre n'est venu me dire qu'il n'était pas ressemblant!"),
      new fmrBlague("Un arbuste dit à un géranium : Espèce d'empoté !."),
      new fmrBlague("Sur le tournage d'un film de Tarzan, l'acteur principal se plaint : \n- A chaque fois que je m'accroche à une liane, le metteur en scène crit : Coupez !"),
      new fmrBlague("Quel est le sport le plus fruité ? La boxe : \ntu prends des pêches plein la poire, tu tombes dans les pommes et tout ça pour des prunes."),
      new fmrBlague("Prudente, la maman allumette recommande à ses enfants: \nEt surtout ne vous grattez pas la tête!"),
      new fmrBlague("Proverbe chinois: \nSi tu tapes ta tête contre une cruche et que ça sonne creux, \nn'en déduis pas forcément que c'est la cruche qui est vide."),
      new fmrBlague("Oui monsieur le commissaire, mon père est maire, ma tante est soeur.\nJ'ai un cousin qui est frère et mon frère est masseur."),
      new fmrBlague("On demande à un grand explorateur : \n- Quelle est la peau de l'animal que vous avez eu le plus de mal à rapporter de vos chasses ? \n- La mienne !"),
      new fmrBlague("Nicolas demande à un copain : \nQu'est-ce que ça veut dire : I don't know ?\net l'autre répond : je ne sais pas !"),
      new fmrBlague("Nicolas demande à sa maman : \n- Elle faisait quoi, comme métier, la Sainte Vierge ? \n- Elle était mère au foyer. \n- Alors, pourquoi elle a mis le petit Jésus à la crèche"),
      new fmrBlague("Monsieur Dubois demande à sa femme : \n- Quelle est la différence entre un accident et une catastrophe ? \n- Heu, je ne sais pas... \n- Ta mère tombe à l'eau, c'est un accident. Quelqu'un la repêche, c'est une catastrophe."),
      new fmrBlague("Madame Dupont dit à son mari: \n- Bouge un peu que je passe un coup de balai! \nIl faut que tout soit propre pour la nouvelle femme de ménage!"),
      new fmrBlague("Madame Dupont achète des oeufs au marché. \n- Ils sont pondus du jour au moins ? Elle s'inquiète : \n- Bien sûr ! La nuit, elles dorment mes poules !"),
      new fmrBlague("Madame dit à Monsieur : \n- Tu te rases avec un rasoir électrique ? \n- Non! répond Monsieur, j'ai peur des coupures de courant!"),
      new fmrBlague("Lorsqu'une voiture de Formule 1 prend un virage à droite à 140 km/h, \nquelle roue tourne le moins vite ? \nRéponse : La roue de secours."),
      new fmrBlague("Lors d'un sondage sur les après-rasages, on demande à un homme dans la rue: \n- Monsieur, que mettez-vous après vous être rasé?\n- Mon pantalon!"),
      new fmrBlague("Le roi souffre des dents. Son dentiste lui dit : \n- Sire, il faudrait changer votre couronne. \n- Ah ça jamais ! répons le roi."),
      new fmrBlague("Le papa dit à Emilie : \n- Tu travailles lentement, tu comprends lentement, tu marches lentement.\nY a-t-il quelque chose que tu fasses vite ?\n- Oui, je me fatigue vite."),
      new fmrBlague("Le dentiste demande au patient: \n- De quel côté mangez-vous? \n- Du côté de la gare, mais je me demande bien ce que ça peut vous faire."),
      new fmrBlague("Le coiffeur dit à son client: \n- Cette mousse ferait pousser des cheuveux sur une boule de pétanque. \n- Très bien. Mais est-ce que ça ne gênerait pas un peu le jeu?"),
      new fmrBlague("La vie d'une ampoule est fragile ...\ncar elle ne tient qu'à un fil !"),
      new fmrBlague("La postière dit à Charlotte : \n- Cette lettre est trop lourde. Il faut ajouter un timbre de 50ct. \n- Oui, mais si j'ajoute un timbre, elle sera encore plus lourde !"),
      new fmrBlague("La maman dit à Julien : \n- Tu as encore mis tes doigts sales sur la porte ! \n- Même pas vrai ! Moi, je l'ouvre à coup de pied !"),
      new fmrBlague("La maman demande à Julien: \n- Que fais-tu? \n- Rien! \n- Et ton frère? \n- Il m'aide!"),
      new fmrBlague("Julien rentre de l'école. Il a le genou écorché. \n- Pauvre chou, tu as dû beaucoup pleurer, compâtit sa maman. \n- C'est pas la peine, y'avait personne."),
      new fmrBlague("Julien demande 10 euros à son père. celui-ci questionne : \n- C'est pour quoi faire ? \n- Pour donner à une vieille dame. \n- Bravo, c'est très bien de vouloir l'aider. Et où est-elle cette dame. \n- Là-bas, elle vend des glaces !"),
      new fmrBlague("Deux voyageurs de commerce discutent: \n- Moi, fait l'un, je traite mes clients comme mes cigarettes. \n- Comment cela? \n- Je les roule toujours moi-même!"),
      new fmrBlague("Deux passants se croisent dans la rue : \n- Tiens, Jean, comme tu as changé : les cheveux, les yeux ... \n- Mais monsieur, je ne m'appelle pas Jean. \n- Ah bon ! Tu as même changé de nom !"),
      new fmrBlague("Deux microbes se rencontrent:\n- Tu es pâle, qu'est-ce que tu as?\n- Je suis malade, j'ai avalé une aspirine."),
      new fmrBlague("Deux grenouilles se parles. il y en a une qui dit : - Quoi quoi quoi.\nL'autre répond : - On ne dit pas quoi, on dit comment"),
      new fmrBlague("Deux gamins discutent :\n- Comment écris-tu Père Noël, avec un L ou deux ?\n- Avec deux sûrement, sinon, il ne pourrait pas voler !"),
      new fmrBlague("Deux esquimaux pêchent sur la banquise. Soudain l'un d'eux s'écrie:\nRentrons vite! C'est l'heure de Hélène et les glaçons!"),
      new fmrBlague("Deux escargots arrivent sur une plage et aperçoivent une limace :\n- Demi-tour ! Nous sommes sur une plage nudiste !"),
      new fmrBlague("Deux chasseurs parlent ensemble :\n- Tiens ! Tu as fait un noeud aux oreilles de ton chien ?\n- Oui, c'est pour penser à acheter du gibier en rentrant !"),
      new fmrBlague("Deux anges font la causette :\n- Quel temps fera-t-il demain ?\n- Nuageux. \n-Ah tant mieux, on pourra s'asseoir !"),
      new fmrBlague("Des frères et soeurs se disputent:\n- Quel âne!\n- Tête de cochon!\n- Espèce de dinde! Leur mère arrive\net crie: Oh la ferme!"),
      new fmrBlague("Dans un coin sombre, deux amoureux s'embrassent.\nDes gamins les regardent. L' un dit a l'autre :\n- Vise un peu, il essaye de lui piquer son chewing-gum !"),
      new fmrBlague("Dans un cocktail, une actrice rencontre une romancière qu'elle déteste.\n- J'ai beaucoup aimé votre dernier livre. Qui vous l'a écrit?\n- Je suis contente qu'il vous ait plu. Qui vous l'a lu?"),
      new fmrBlague("Dans le train, le contrôleur dit à une vieille dame: \n- Votre billet est pour Bordeaux. Or ce train va à Nantes. \n- C'est ennuyeux, grommelle la voyageuse. \nEt ça arrive souvent au chauffeur de se tromper comme ça?"),
      new fmrBlague("Dans le grand océan, une petite vague est amoureuse du vent. Celui-ci lui demande tendrement: \n- Tu veux que je te fasse une bourrasque ou un ouragan? \n- Oh non, je veux juste une petite bise..."),
      new fmrBlague("Dans la rue, un homme demande à Madame Dupont : \n- Vous n'auriez pas vu un policier ? \n- Non.\n- Alors donnez-moi votre sac à main."),
      new fmrBlague("Chez le dentiste: \n- Vous avez une dent morte. Je vous fais une couronne? \n- Non merci, enterrez-la sans cérémonie."),
      new fmrBlague("Charlotte va voir sa maman et demande : \n- Est-ce que je pourrais avoir du chocolat ? \n- On dit comment ? S'il... s'il ? \n- S'il en reste encore ?"),
      new fmrBlague("Charlotte regarde un mille-feuilles qui coûte 4 euros.\nElle entre et dit à la boulangère :\n- Je voudrais 500 feuilles, parce que je n'ai que 2 euros"),
      new fmrBlague("Charlotte part à la visite médicale avec son petit flacon d'urine. Elle demande : \n- C'est pour quoi faire ? \n- A ton avis ? répond sa maman \n- C'est pour remercier le docteur ?"),
      new fmrBlague("Charlotte demande à Nicolas : \n- Tu sais pourquoi il y a des trous au fond des pots de fleurs ? \n- Oui, c'est pour qu'on puisse prendre la température des plantes"),
      new fmrBlague("C'est une jolie petite antenne de T.V. qui est tombée amoureuse d'un paratonnerre.\nElle murmure: dis, tu y crois toi, au coup de foudre?"),
      new fmrBlague("C'est un habitant du village de Poil. On lui demande: \n- Où êtes-vous né? \n- A Poil! \n- Et bien moi aussi figurez-vous!"),
      new fmrBlague("Cela fait une semaine que je vous soigne pour une jaunisse, \ndit le médecin à son client, \net c'est maintenant que vous me dites que vous êtes chinois!"),
      new fmrBlague("Au restaurant, Monsieur Dupont s'écrie: \n- Garçon, il y a une mouche qui nage dans mon assiette. \n- Oh, c'est encore le chef qui a mis trop de potage.\nD'habitude, elles ont pied!"),
      new fmrBlague("Au restaurant, le garçon demande au client: \n- Comment avez-vous trouvé le beefsteak? \n- Tout à fait par hasard, en soulevant une frite!"),
      new fmrBlague("Au cinéma, deux bavardes n'arrêtent pas de discuter. Excédé, leur voisin proteste : \n- S'il vous plait, je n'entend rien du tout. \n- Et alors, ça vous regarde, ce que nous disons."),
      new fmrBlague("Alors mon cher, ces vacances? Où étiez-vous? \n- Oh, la première semaine, j'étais dans les Alpes et les deux suivantes,\nj'étais dans le plâtre."),
      new fmrBlague("A l'entrée d'un pont, il est inscrit sur une pancarte : \nNe pas passer à deux, sinon le pont casse. \nUne homme lit la pancarte et traverse le pont. \nLe pont casse car ... un homme averti en vaut deux."),
      new fmrBlague("A combien rouliez-vous? Demande le gendarme. \nA deux seulement, mais si vous voulez monter, il reste de la place."),
      new fmrBlague("- Vous avez eu beau temps pendant vos vacances? \n- Super! Il n'a plus que deux fois.\nLa première fois, pendant une demi-journée, \net la deuxième, pendant 29 jours."),
      new fmrBlague("- S'il te plait mon Papichou, tu veux bien me donner 5 F demande Julien à son grand-père ? \n- D'accord, si tu me le demandes correctement. \n- Sois cool, vieux, fille-moi 20 balles !"),
      new fmrBlague("- Moi j'ai toute l'année des ampoules dans les mains. \n- Vous faites un travail difficile? \n- Non, je suis vendeur au rayon électricité. Pourquoi faut-il aimer son prochain? \n- Parce que les autres sont loin."),
      new fmrBlague("- Les gens devraient tout le temps dormir la fenêtre ouverte.\n- Pourquoi, vous êtes médecin? \n- Non, je suis cambrioleur."),
      new fmrBlague("- Je vais acheter cette toile dit le client au peintre. \n- C'est une affaire, Monsieur. J'y ai passé dix ans de ma vie. \n- Dix ans? Quel travail! \n- Eh oui: deux jours pour la peindre et le reste pour réussir à la vendre!"),
      new fmrBlague("- J'ai battu un record.\n- Ah bon, lequel ?\n- J'ai reussi a faire en 15 jours un puzzle\nsur lequel il y avait écrit de 3 a 5 ans."),
      new fmrBlague("- Il faut être bon avec les animaux, explique le papa de Julien.\n- Oui papa, il ne faut pas les traiter comme des bêtes."),
      new fmrBlague("- Ecoute, dit la maman à sa petite fille,\nsi tu es sage, tu iras au ciel,\net si tu n'es pas sage, tu iras en enfer.\n- Et qu'est-ce que je dois faire pour aller au cirque?"),
      new fmrBlague("- Chéri, dis-moi ce que tu préfères,\nune femme jolie, ou une femme intelligente?\n- Ni l'un, ni l'autre, chérie,\ntu sais bien que je n'aime que toi."),
      new fmrBlague("- Chauffeur, soyez prudent, à chaque virage j'ai peur de tomber dans le ravin! \n- Madame n'a qu'à faire comme moi, fermer les yeux!"),
      new fmrBlague("- Allô Police ! Je viens d'écraser un poulet. Que dois-je faire ? \n- Et bien , plumez-le et faites-le cuire à thermostat 6. \n- Ah bon ! Et qu'est-ce que je fais de la moto ?"),
      new fmrBlague("- A ma droite, il y avait un lion féroce, \nà ma gauche, un tigre prêt à bondir, \nderrière des éléphants énormes,...\n- Alors ? Qu'as-tu fait pour t'en sortir ? \n- J'ai sauté au bas du manège !"),
      new fmrBlague("Quel est le comble du Torero ?\nQue le taureau soit vache !"),
      new fmrBlague("Monsieur, savez vous que votre chien aboie toute la nuit ?\nOh, ca ne fait rien, il dort toute la journée."),
      new fmrBlague("Un client revient chez le pharmacien :\nVotre dentifrice a un goût infect.\nEt alors ? De toute façon, vous le recrachez."),
      new fmrBlague("Quelle est la plante qu'on arrose jamais et qu'on écrase sans qu'elle ne s'abîme?\n- La plante des pieds."),
      new fmrBlague("Un fou fait des bonds au dessus d'un plat de spaghetti. Il explique : je saute un repas."),
      new fmrBlague("C'est un esquimau sur la banquise, qui se les gèle en attendant sa copine. Au bout d'une longue attente, il sort un thermomètre de sa poche et dit :\n- Si elle n'est pas là à moins 20, je m'en vais."),
      new fmrBlague("Qu'est-ce qu'un homme avec une mitraillette dans un champ de blé ?\n- Un céréale killer..."),
      new fmrBlague("Quatre éléphants sont à bord d'une coccinelle. Lequel d'entre eux conduit ?\n- Celui qui a le permis de conduire !"),
      new fmrBlague("Que fait un crocodile quand il rencontre une superbe femelle ? Il Lacoste !"),
      new fmrBlague("Quelle est la différence entre un crocodile et un alligator ?\n- C'est Caïman la même chose..."),
      new fmrBlague("Un groupe d'anglais arrive dans la brousse pour chasser des singes, il engage un chasseur professionnel qui leur indique comment cela va se passer :"),
      new fmrBlague("Pourquoi les chiens se lèchent-ils toujours les bijoux de famille ? \n- Ils en sont capables, eux ! "),
      new fmrBlague("Savez-vous pourquoi les pompiers portent des bretelles rouges ?\n- C'est pour tenir leur pantalon !"),
      new fmrBlague("L'autre jour, j'ai failli perdre ma montre. Elle était arrêtée et moi je continuais à marcher."),
      new fmrBlague("L'autre jour, j'ai invité des amis à la maison pour manger une omelette.\n- Ils ne sont pas venus.\n- J'ai donc mangé une omelette sans eux."),
      new fmrBlague("Si vous avez un chien qui est soudainement aphone, donnez-lui une soucoupe de lait.\n- Il la boit (il aboie)."),
      new fmrBlague("- Si vous avez un chien, dans le genre de ceux qui ont du poil partout et où on a des difficultés à savoir de quel côté est la tête, tendez un morceau de sucre ... le côté qui mange le sucre, c'est la tête."),
      new fmrBlague("- Un condamné à mort doit passer à la chaise électrique, pour avoir écrasé de nombreux piétons avec sa voiture. Au moment de la sentence, le bourreau abaisse le levier mais rien ne se passe. Savez-vous pourquoi ? C'est simplement parce qu'il est mauvais conducteur."),
      new fmrBlague("Je connais un opticien menuisier. Il fabrique des lunettes de WC en bois."),
      new fmrBlague("Je connais un type, il est tellement petit que ses cheveux sentent les pieds"),
      new fmrBlague("Je connais quelqu'un qui a réussi à croiser un pigeon avec un pivert. Quand il porte un message, il frappe à la porte."),
      new fmrBlague("C'est Toto qui rencontre un pote sur le chemin de l'école et lui dit :\n- Je vais avoir un zéro en math !!\n- Tu en es sur ?\n- Aussi sur que 2 et 2 font 5"),
      new fmrBlague("Quel est le comble pour un médecin ?\n- Ausculter son crayon pour voir s'il a bonne mine..."),
      new fmrBlague("Un fou téléphone à un autre fou :\n- Allo ? Je suis bien au 20 73 67 ?\n- A non, monsieur, vous faîtes erreur, ici on n'a pas le téléphone."),
      new fmrBlague("A l'occasion d'un sondage sur les lotions après-rasage, on demande a un homme :\n- S'il vous plaît, qu'est-ce que vous mettez après vous être rasé ?\n- Mon pantalon."),
      new fmrBlague("De quelle couleur sont les petits pois ?\n- Rouges parce que les petits pois sont rouges ! (les petits poissons rouges)"),
      new fmrBlague("Qu'y a t'il de plus difficile que de mettre une éléphante enceinte dans une 2CV ?\n- Mettre enceinte une éléphante dans une 2CV. "),
      new fmrBlague("Savez-vous pourquoi les éléphants se déplacent en troupeau compact ?\n- Parce que c'est celui du milieu qui a la radio...\nEt savez-vous pourquoi les rhinocéros se déplacent en troupeau compact ?\n- Pour faire croire aux éléphants qu'eux aussi, ils ont la radio..."),
      new fmrBlague("Qu'est-ce qui mesure 2m sur 3, pèse 130 kg, et vole allègrement dans l'air printanier ? Un canari plutôt balaise..."),
      new fmrBlague("A Deubert, un petit village de Loraine, un incendie s'est déclaré dans une communauté de nains.\nUne enquête a aussitôt été ouverte sur l'affaire des petits grillés de Deubert."),
      new fmrBlague("E.T. dit à sa mère :\n- ils étaient extra tes restes"),
      new fmrBlague("Un invité murmure à sa voisine :\n- Le champagne vous rend jolie.\n- Mais je n'en ai pas bu une seule coupe.\n- Oui, mais moi j'en suis à ma dixième."),
      new fmrBlague("Quelle est la différence entre un bébé et un crocodile ?\n- Le bébé fait une mare dans son lit, et le crocodile fait son lit dans la mare."),
      new fmrBlague("La maîtresse à Toto :\n- Conjugue-moi le verbe savoir à tous les temps.\n- Je sais qu'il pleut,\nje sais qu'il fait beau,\nje sais qu'il neige."),
      new fmrBlague("- Je suis inquiet, je vois des points noirs.\n- Tu as vu un oculiste ?\n- Non, des points noirs !"),
      new fmrBlague("Une petite fille demande à sa maman :\n- Maman, pourquoi la nuit n'a-t-elle qu'un oeil ?\n- Qu'est-ce que tu racontes ?\n- Ben oui, papa a dit qu'il n'a pas pu fermer l'œil de la nuit."),
      new fmrBlague("- Dis moi, on est quel jour ?\n- Mercredi.\n- Hein ?!! Déjà !?!?!?"),
      new fmrBlague("Il y a trois sortes de personnes. Celles qui savent compter et celles qui ne savent pas."),
      new fmrBlague("Une souris et un éléphant courent dans la savane... La souris se retourne et dit :T'as vu la poussière qu'on fait !"),
      new fmrBlague("Une pomme est rouge, jaune, et verte. Comment l'appelle-t-on ?\n- On la pèle avec un couteau."),
      new fmrBlague("Que disent deux chats quand ils sont amoureux ?\n- On est félin pour l'autre."),
      new fmrBlague("Qu'est-ce qu'un chou au fond d'une baignoire ? Un choumarin !"),
      new fmrBlague("J'ai trois têtes, dix bras, quatre jambes et trois pieds. Qui suis-je ? Un menteur"),
      new fmrBlague("C'est un fou qui promène son peigne en laisse et qui rencontre le directeur de son asile.\n- Bonjour Serge, comment va Médor aujourd'hui ?\n- Mais enfin monsieur le directeur vous voyez bien que c'est un peigne !\n- Heu, ben oui.\nAussitôt le directeur parti :On l'a bien eu Médor, hein ?"),
      new fmrBlague("J'ai trois nez, deux bouches, quatre yeux et cinq oreilles. Que suis-je ?\n- Horrible."),
      new fmrBlague("Qu'est-ce qui est vert et qui pend des arbres dans la savane africaine ?\n- De la morve de girafe."),
      new fmrBlague("Pourquoi la marine belge a-t-elle perdu tous ses sous-marins ?\n- Parce qu'elle a fait une journée portes ouvertes !"),
      new fmrBlague("Deux fous dans une cellule. Un des deux colle des timbres sur le corps nu de l'autre. Le directeur lui demande ce qu'il fait. Le fou lui répond :\n- C'est tout simple, je l'affranchis avant de me l'envoyer."),
      new fmrBlague("Un fou écrit une lettre. Le directeur lui demande :\n- A qui écrivez-vous ?\n- A moi. \n- Et qu'est-ce que vous avez mis ?\n- Je ne sais pas, monsieur le directeur je ne l'ai pas encore reçue !"),
      new fmrBlague("Un fou est suspendu à une poutre du plafond. L'inspecteur demande au directeur pourquoi. Le directeur lui dit :\n- C'est parce qu'il se prend pour un lustre.\n- Ne peut-on pas le faire descendre maintenant ?\n- Oui, on le peut, mais avec quoi va-t-on s'éclairer ce soir ?"),
      new fmrBlague("3 fous passent un test avant la sortie. \n- Combien font 3 fois 3 ? Le 1er répond :\n- 648. Il n'est pas guéri. Le 2nd répond :\n- Vendredi. Idem pour celui-là. \nLe 3ème répond : - Cela fait neuf.\n- Bien! Tu es guéri! Mais comment as-tu fait pour trouver ?\n- C'est tout simple, j'ai divisé 648 par vendredi !"),
      new fmrBlague("Un type va voir le psychiatre :\n- Docteur, j'ai un problème. Ma femme se prend pour moi.\nLe médecin lui répond :\n- Bon, alors envoyez-la-moi. \nLe type répond : Mais, docteur, je suis là !"),
      new fmrBlague("Un sous-marin se heurte à un poisson rouge qui venait de sa gauche.\nQui est en tort ?\n- Le sous-marin, parce qu'il n'avait rien à faire dans un bocal de poisson rouge !"),
      new fmrBlague("Un homme qui se prenait pour Napoléon déclare à son psychiatre :\n- Docteur, je suis complètement guéri. Je ne me prends plus du tout pour Napoléon. \n- Très bien, dit le médecin. Est-ce qu'il y a encore quelque chose qui vous tracasse ?\n- Oui docteur, pour ma retraite, quel climat me conviendrait le mieux, Sainte-Hélène ou l'île d'Elbe, à votre avis ?"),
      new fmrBlague("Une annonce dans la presse :\nLe monsieur qui a quitté l'asile ce matin au volant de la voiture du directeur et qui se prend pour Napoléon est prié de rentrer d'urgence : Joséphine est malade."),
      new fmrBlague("Chez le gynécologue, 2 femmes enceintes discutent. L'une dit :\n- Il faut faire attention aux films qu'on regarde. Ma mère avait été voir Les Deux Orphelines et nous étions des jumelles avant d'être orphelines. Une autre amie a vu Les trois Mousquetaires et elle a eu des triplés. La deuxième femme dit alors :\n- Zut! je viens de voir Ali Baba et les 40 Voleurs !"),
      new fmrBlague("Deux hommes attendent fébrilement dans la salle d'attente d'une maternité. La porte s'ouvre et une infirmière s'adresse, souriante, à l'un des deux hommes.\n- Compliments, Monsieur ! Vous êtes un heureux papa...\nL'autre type se lève, furieux :\n- Mais madame, je suis pourtant arrivé avant lui !"),
      new fmrBlague("Comment fait-on les petits suisses ?\n- Comme les petits français."),
      new fmrBlague("Un chameau demande à un dromadaire :\n- Comment ça va ?\n- Bien, je bosse, et toi ?\n- Je bosse, je bosse !"),
      new fmrBlague("Une mère dit à son fils :\n- N'oublie pas que nous sommes sur terre pour travailler.\n- Bon, alors moi, plus tard, je serai marin."),
      new fmrBlague("Deux microbes se rencontrent :\n- Tu es pâle, qu'est-ce que tu as ?\n- Je suis malade, j'ai avalé une aspirine."),
      new fmrBlague("L'institutrice demande à Julien :\n- Quand je dis il pleuvait, de quel temps s'agit-il ?\n- D'un sale temps, madame."),
      new fmrBlague("La maman d'Emilie n'est pas contente :\n- Regarde, le lait a débordé. Je t'avais pourtant bien demandé de surveillé ta montre.\n- Mais je l'ai fait. Il était exactement 8h10 quand le lait a débordé."),
      new fmrBlague("- Es-tu coiffeur demande Julien à son grand-père ?\n- Non, pourquoi ?\n- Parce que maman a dit que tu frisais la cinquantaine, et papa que tu allais nous raser toute l'après-midi."),
      new fmrBlague("Le coiffeur dit à son client :\n- Cette mousse ferait pousser des cheveux sur une boule de pétanque.\n- Très bien. Mais est-ce que ça ne gênerait pas un peu le jeu ?"),
      new fmrBlague("Dans le train, le contrôleur dit à une vieille dame :\n- Votre billet est pour Bordeaux. Or ce train va à Nantes.\n- Ca c'est ennuyeux, grommelle la voyageuse. Et ça arrive souvent au chauffeur de se tromper comme ça ?"),
      new fmrBlague("Un policier demande à un jeune homme qui court autour d'une école :\n- Que faites-vous ?\n- Je poursuis mes études.\nEt vous ? Demande-t-il à un autre qui court encore plus vite.\n- Oh, moi, je fais du rattrapage."),
      new fmrBlague("Un petit veau rentre de l'école et présente son bulletin trimestriel, où ses parents lisent : Peut faire meuh."),
      new fmrBlague("Deux aspirateurs se rencontrent. \n- Vous n'avez pas l'air d'aller très bien, dit l'un. \n- Non, dit l'autre, j'ai une indigestion. Hier j'ai mangé trop de moutons."),
      new fmrBlague("Un vieux citron fait l'éducation de son fils. Surtout, fiston, ne sois jamais pressé."),
      new fmrBlague("Un ver et un hérisson ont un jour un bébé. A quoi ressemble-t-il ?\n- A du fil de fer barbelé."),
      new fmrBlague("Un pêcheur explique à un Parisien en vacances :\n- Vous savez, hier il y a eu une tempête et le port en a souffert. La jetée a été entièrement détruite par un raz-de-marée !\nLe Parisien répond :\n- Jamais je n'aurais cru qu'un rat puisse faire tant de dégâts !"),
      new fmrBlague("Un chevalier du Moyen Age rentre chez lui après de nombreuses années de croisade. Lorsqu'il retire son armure, \nsa femme s'exclame :\n- Comme tu es bronzé !\n- Non, répond-il, c'est de la rouille !"),
      new fmrBlague("Pourquoi as-tu rompu tes fiançailles, elle était charmante !\n- Oui, mais elle était institutrice et chaque fois que j'arrivais en retard à un rendez-vous, il fallait que j'apporte un mot d'excuse de mes parents !"),
      new fmrBlague("Un enfant assiste à un mariage. Après la cérémonie, il dit à son petit copain :\n- Tu as vu ?\n- Quoi ?\n- La mariée a dû changer d'avis dans l'église.\n- Mais pourquoi ?\n- Parce que, je l'ai vue entrer au bras d'un vieux monsieur et elle est ressortie au bras d'un jeune !"),
      new fmrBlague("Un médecin prend le pouls de son client :\n- vous êtes en parfaite santé, votre pouls est aussi régulier qu'un mouvement d'horlogerie !\n- C'est normal, répond le patient, vous avez le doigt sur ma montre !"),
      new fmrBlague("Un Parisien en vacances à la campagne passe devant un champ et demande au paysan :\n- Mais comment faites-vous pour obtenir des radis aussi gros ?\n- Ce n'est pas compliqué, Monsieur : j'ai semé des graines de betterave rouge !"),
      new fmrBlague("- Je suis inquiet, je vois des points noirs.\n- Tu a vu l'oculiste ? \n- Non, des points noirs !"),
      new fmrBlague("- Garçon, il y a une mouche dans ma salade !\n- Ne vous inquiétez pas, monsieur. Elle n'en a pas pour longtemps : vous voyez l'araignée sur le bord ?"),
      new fmrBlague("Un juge d'application des peines inspecte le quartier des fortes têtes. Il voit un prisonnier enchaîné et lui demande :\n- Alors, mon gaillard, vous vous plaisez ici ? L'autre ricane :\n- Ouais, c'est un endroit auquel je suis toujours très attaché !"),
      new fmrBlague("Un vieux dragueur chauve sur le dessus de la tête rencontre une jeunette qui lui fait observer qu'il a perdu des cheveux sur le haut du crâne. \n- Mais c'est un signe d'intelligence !\n- Oui, mais vous êtes donc un peu con sur les bords !"),
      new fmrBlague("Une souris rencontre sa copine :\n- J'ai décidé de me mettre au régime, lui dit-elle. \n- Tu ne manges plus ton gruyère alors ?\n- Si, mais je ne mange plus que les trous !"),
      new fmrBlague("Un éléphant et une souris se présentent au bord d'un lac gelé. L'éléphant hésite à s'élancer. La souris le rassure :\n- Je vais y aller la première, dit-elle, pour voir si la glace tient le coup !"),
      new fmrBlague("Pourquoi les souris gnignient ?\n- Parce que les rats gnagnaent !"),
      new fmrBlague("Pourquoi Mario Bross ?\n- Parce que Mickey Mouse..."),
      new fmrBlague("Pourquoi il n'y a pas d'haut-parleurs dans le ciel ?\n- Parce que Jésus Christ."),
      new fmrBlague("C'est qui le chinois le plus rapide du monde ?\n- WOOOOOONNNGGGG !"),
      new fmrBlague("Pourquoi les plongeurs sous-marin plongent-ilstoujours en arrière et jamais en avant ?\n- Parce que sinon ils tombent dans le bateau."),
      new fmrBlague("Comment reconnaît-on un écureuil d'une fourchette ?\n- Il faut les mettre au pied d'un arbre. Celui qui monte c'est l'écureuil."),
      new fmrBlague("Comment reconnaît-on un perroquet mâle d'un perroquet femelle ?\n-On les met tous les 2 dans un frigo, le premier qui sort en disant on se les gèle c'est le mâle."),
      new fmrBlague("Qu'est-ce que Benjamin Franklin a dit lorsqu'il a découvert l'électricité ?\n- OUCH !!!!!"),
      new fmrBlague("Si la tour de Pise penche vers la gauche, c'est qu'il va pleuvoir. Si elle penche vers la droite, c'est que vous arrivez par l'autre côté de la rue."),
      new fmrBlague("Qu'est ce qu'il y a au-dessus des montagnes et qui finit par ar ?\n- Euh, des montagnards ?\n- Non, de la neige, CONNARD !\n- Et tu sais ce qu'il y a au-dessus des montagnes et qui finit par ir ?\n- Je sais pas\n- De la neige CONNARD, je viens de te le dire !"),
      new fmrBlague("Vous connaissez l'histoire de la chaise ? Non ?\n- C'est dommage, elle est pliante..."),
      new fmrBlague("C'est une fois 2 gars sur un immeuble. \nIl y en a un qui est saute en bas et l'autre en collant."),
      new fmrBlague("C'est un schtroumf qui court, il tombe et se fait un bleu."),
      new fmrBlague("C'est un zéro qui rencontre un huit et il lui dit :\n- tient, tu as mis une ceinture aujourd'hui..."),
      new fmrBlague("Pourquoi les flamands roses lèvent une patte en dormant ?\nParce que s'ils levaient les deux, ils tomberaient."),
      new fmrBlague("Pourquoi on met une selle sur un cheval ?\n- Parce qu'il si on la met dessous, elle tombe.\nOU\n- Parce qu'il ne peut pas se la mettre tout seul."),
      new fmrBlague("Que dit le hibou a sa femme le jour de l'an ?\n- Je te chouette une bonne année."),
      new fmrBlague("Quel est la plus grosse hantise d'une chauve-souris ?\n- Avoir la chiasse pendant qu'elle dort."),
      new fmrBlague("C'était une fois, 2 boulettes de viande qui jouait à cache-cache.\ny'en a une qui dit à l'autre : - où STEAK HACHÉ ?"),
      new fmrBlague("Qu'est ce qu'un steak derrière un arbre ?\n- Un steack caché."),
      new fmrBlague("Quelle est différence entre Tintin et le Capitaine Haddock ?\n- Ils ont tous les deux une barbe sauf Tintin."),
      new fmrBlague("Pourquoi les chats ont peur de l'eau ?\nparce que dans l'eau, minérale...(minet râle)"),
      new fmrBlague("Qu'est-ce que les pygmées ont dit quand ils ont vu les premiers éléphants ?\n- ooooooh des éléphants !\nQu'ont-ils dit lorsqu'ils virent les premiers éléphants avec des lunettes de soleil ?\n- ils ne les ont pas reconnus."),
      new fmrBlague("Qu'y a t'il avant et après le retour du jedi ?\n- le retour du mercredaïe et le retour du vendredaïe."),
      new fmrBlague("Que prend un éléphant quand il entre dans un bar ?\n- De la place."),
      new fmrBlague("- Docteur, je suis amnésique\n- ah ! et depuis quand ?\n- depuis quand quoi ?"),
      new fmrBlague("Qu'est qu'un cochon qui rit ? Un porc tout gai."),
      new fmrBlague("Une petite fille rentre de l'école et demande à son père :\n- Tu connais la dernière ?\n- Non ?\n- Ben c'est moi !"),
      new fmrBlague("C'est deux vaches qui discutent dans un prés :\n- Ca te fais pas peur toi toutes ces histoires de vaches folles. Moi ça me fout les jetons.\n- Non. Moi je m'en fiche j'suis un canard."),
      new fmrBlague("Savez-vous ce qu'est un oula-oula ?\n- C'est un oiseau avec de toutes petites pâtes, mais une énorme paire de couilles et, quand il se pose, il fait : Ooula oula !"),
      new fmrBlague("Deux chèvres, Baba et Babi sont sur une barque, au milieu d'un étang. Tout a coup, Baba tombe à l'eau, que se passe-t-il alors ?\n- Baba coule et Babi bêle."),
      new fmrBlague("À la douane néerlandaise, le douanier\n- Vous avez de l'alcool ?\n- Non.\n- Vous avez des armes ?\n- Non.\n- Vous avez de la drogue ?\n- Non.\nAprès avoir jeté un bref coup d'œil alentours, le douanier :\n- Vous en voulez ?"),
      new fmrBlague("Un gars vient d'être admis à l'asile. A peine entré, il s'écrie :\n- Mais il y a un monde fou là dedans !"),
      new fmrBlague("Un casse-pieds demande à un peintre :\n- Pourquoi ne peignez-vous que des paysages ?\n- Parce que jamais un arbre n'est venu me dire qu'il n'était pas ressemblant !"),
      new fmrBlague("Quelle est la différence entre une échelle et un pistolet ?\n- L'échelle sert à monter, le pistolet à descendre."),
      new fmrBlague("Alors cet examen demande papa kangourou à sa fille qui rentre de l'école.\n-Pas de problème, c'est dans la poche."),
      new fmrBlague("Pourquoi les femmes parlent-elles moins en Février ?\n- Parce qu'il n'y a que 28 jours"),
      new fmrBlague("A la piscine, un nageur se fait enguirlander parce qu'il a fait pipi dans l'eau.\n- Mais enfin, proteste-t-il, vous exagérez, je ne suis pas le seul à faire çà !\n-Si, monsieur, du haut du plongeoir, vous êtes le seul !"),
      new fmrBlague("La maman demande à Julien :\nQue fais-tu ? \nRien !\nEt ton frère ?\nIl m'aide !"),
      new fmrBlague("Maman demande à Julien :\n- Pourquoi as tu de mauvaises notes ?\n- Parce que ce n'est pas moi qui les mets !"),
      new fmrBlague("Des frères et sœurs se disputent :\n- Quel âne !\n- Tête de cochon.\n- Espèce de Dinde.\nLeur mère arrive et crie : Oh la ferme !"),
      new fmrBlague("Un homme va acheter un lit et demande qu'il soit très solide. Le vendeur s'étonne :\nPourtant, vous n'êtes pas très lourd.\nNon, mais j'ai le sommeil lourd."),
      new fmrBlague("Deux chiens se promènent.\nTout à coup, l'un d'eux se met à frétiller. \nTu as vu, dit-il, un réverbère neuf ! Ca s'arrose !"),
      new fmrBlague("Une poule rencontre une autre poule. \n- Tu viens, lui dit-elle, on va prendre un ver ?")
   };

//******************************************************************************
// fmrBlague()
//******************************************************************************
   private fmrBlague(String blg)
   {
      this.blg = blg;
   }

//******************************************************************************
// get()
//******************************************************************************
   public static String get(long seed)
   {
      Random generator = new Random(seed);
      int rnd = generator.nextInt(blague.length);
      return blague[rnd].blg;
   }
}