package fr.ozf.fmr;

import java.util.Random;

public class fmrCitation
{

    private String cit;
    private static final fmrCitation citation[] =
    {
        new fmrCitation("Croire en quelque chose et ne pas le vivre, c'est malhonnête. [Gandhi]"),
        new fmrCitation("Faites des bêtises, mais faites-les avec enthousiasme. [Colette]"),
        new fmrCitation("Ce que j'aime dans les voyages, c'est l'étonnement du retour. [Stendhal]"),
        new fmrCitation("Le projet est le brouillon de l'avenir. Parfois, il faut à l'avenir des centaines de brouillons. [Jules Renard]"),
        new fmrCitation("C'est dans le mépris de l'ambition que doit se trouver l'un des principes essentiels du bonheur sur la terre. [Edgar Allan Poe]"),
        new fmrCitation("Le pessimiste voit la difficulté dans chaque opportunité. L'optimiste voit l'opportunité dans chaque difficulté. [Sir Winston Churchill]"),
        new fmrCitation("La vérité ne se dégage pas de la polémique, mais des oeuvres qu'on a faites. [Paul Gauguin]"),
        new fmrCitation("Dix mille difficultés ne font pas un doute. [Isaac Newton]"),
        new fmrCitation("N'attends pas que les événements arrivent comme tu le souhaites. Décide de vouloir ce qui arrive... et tu seras heureux. [Epictète]"),
        new fmrCitation("La meilleure façon d'imposer une idée aux autres, c'est de leur faire croire qu'elle vient d'eux. [Alphonse Daudet]"),
        new fmrCitation("L'homme qui est pessimiste à 45 ans en sait trop, celui qui est optimiste après n'en sait pas assez. [Mark Twain]"),
        new fmrCitation("La simplicité est la sophistication suprême. [Léonard de Vinci]"),
        new fmrCitation("Votre temps est limité, ne le gâchez pas en menant une existence qui n'est pas la vôtre. [Steve Jobs]"),
        new fmrCitation("La lâcheté tend à projeter sur les autres la responsabilité qu'on refuse. [Julio Cortazar]"),
        new fmrCitation("Les mouettes naissent des mouchoirs que l'on agite au départ du bateau. [Ramon Gomez de la Serna]"),
        new fmrCitation("Même les rencontres de hasard sont dues à des liens noués dans des vies antérieures. [Haruki Murakami]"),
        new fmrCitation("Rien n'est plus rare qu'un tyran qui vieillit. [Thalès]"),
        new fmrCitation("L'art est le plus beau des mensonges. [Claude Debussy]"),
        new fmrCitation("La culture ne s'hérite pas, elle se conquiert. [André Malraux]"),
        new fmrCitation("Un seul mot, usé, mais qui brille comme une vieille pièce de monnaie : merci ! [Pablo Neruda]"),
        new fmrCitation("Les hommes ont de grandes prétentions et de petits projets. [Vauvenargues]"),
        new fmrCitation("Si je dors je dors pour moi ; si je travaille, je ne sais pour qui ce sera. [Johann Wolfgang von Goethe]"),
        new fmrCitation("L'homme se distingue de l'animal en ceci qu'il est doué d'arrière-pensées. [Antoine Blondin]"),
        new fmrCitation("Le monde entier est cruel à l'intérieur et cinglé en surface. [David Lynch - Dialogue du film américain Sailor et Lula]"),
        new fmrCitation("La justice sans la force est impuissante, la force sans la justice est tyrannique. [Blaise Pascal]"),
        new fmrCitation("Une poule est l'artifice qu'utilise un oeuf pour produire un autre oeuf. [Umberto Eco]"),
        new fmrCitation("Dans chaque église, il y a toujours quelque chose qui cloche. [Jacques Prévert]"),
        new fmrCitation("Le plaisir peut s'appuyer sur l'illusion, mais le bonheur repose sur la réalité. [Chamfort]"),
        new fmrCitation("La liberté c'est de ne jamais avoir à dire qu'on est désolé. [Sidney Lumet]"),
        new fmrCitation("Etre en vacances c'est n'avoir rien à faire et avoir toute la journée pour le faire. [Robert Orben]"),
        new fmrCitation("L'héroïsme, c'est encore la meilleure façon de devenir célèbre quand on n'a pas de talent. [Pierre Desproges]"),
        new fmrCitation("Le chrétien est un mauvais païen, converti par un mauvais juif. [Simone Weil]"),
        new fmrCitation("- Je vous apporte mes voeux.- Merci, je tâcherai d'en faire quelque chose. [Jules Renard]"),
        new fmrCitation("Savoir écouter, c'est posséder, outre le sien, le cerveau des autres. [Léonard de Vinci]"),
        new fmrCitation("De toutes les écoles que j'ai fréquentées, c'est l'école buissonnière qui m'a paru la meilleure. [Anatole France]"),
        new fmrCitation("Le patriotisme c'est l'amour des siens.Le nationalisme c'est la haine des autres. [Romain Gary]"),
        new fmrCitation("Ce qui m'effraie, ce n'est pas l'oppression des méchants ; c'est l'indifférence des bons. [Martin Luther King]"),
        new fmrCitation("C'est un ami dont je ne connais pas le nom, et je le connais depuis trop longtemps pour lui demander. [Georges Feydeau]"),
        new fmrCitation("L'automne est le printemps de l'hiver. [Henri de Toulouse-Lautrec]"),
        new fmrCitation("La liberté, c'est la faculté de choisir ses contraintes. [Jean-Louis Barrault]"),
        new fmrCitation("Objectivité ne signifie pas impartialité mais universalité. [Raymond Aron]"),
        new fmrCitation("Veux-tu vivre heureux ? Voyage avec deux sacs, l'un pour donner, l'autre pour recevoir. [Johann Wolfgang von Goethe]"),
        new fmrCitation("Aimez le chocolat à fond, sans complexe ni fausse honte, car rappelez-vous : ?sans un grain de folie, il n'est point d'homme raisonnable.? [François de La Rochefoucauld]"),
        new fmrCitation("Le problème avec le fait de ne rien faire, c'est qu'on ne sait jamais quand on a fini. [Edna Wolf]"),
        new fmrCitation("On ne fait jamais attention à ce qui a été fait ; on ne voit que ce qui reste à faire. [Marie Curie]"),
        new fmrCitation("Vivez si m'en croyez, n'attendez à demain. Cueillez dès aujourd'hui les roses de la vie. [Pierre de Ronsard]"),
        new fmrCitation("Si vous devez cent dollars à la banque, c'est votre problème. Si vous devez cent millions de dollars à la banque, c'est le problème de la banque. [Jean-Paul Getty]"),
        new fmrCitation("Une carrière, c'est fantastique, mais on ne peut pas se blottir contre elle la nuit quand on a froid. [Marilyn Monroe]"),
        new fmrCitation("Il faut se méfier des ingénieurs, ça commence par la machine à coudre, ça finit par la bombe atomique. [Marcel Pagnol]"),
        new fmrCitation("N'acceptez aucun compromis. Vous êtes tout ce que vous avez. [Janis oplin]"),
        new fmrCitation("La connaissance parle, mais la sagesse écoute. [Jimi Hendrix]"),
        new fmrCitation("N'essayez pas de devenir un homme qui a du succès. Essayez de devenir un homme qui a de la valeur. [Albert Einstein]"),
        new fmrCitation("Notre vie vaut ce qu'elle nous a coûté d'efforts. [François Mauriac]"),
        new fmrCitation("Il y a une limite au bonheur qu'on peut tirer de son travail. On est même d'autant plus heureux qu'on passe moins de temps au travail. [Scott Adams]"),
        new fmrCitation("Délaisse les grandes routes, prends les sentiers. [Pythagore]"),
        new fmrCitation("Heureux les gens qui ne recherchent pas d'oasis dans le désert de leur coeur ! [André Giroux]"),
        new fmrCitation("Si vous voulez une place au soleil, il faudra vous résigner à supporter quelques coups de soleil. [Abigail Van Buren]"),
        new fmrCitation("Dans chaque église, il y a toujours quelque chose qui cloche. [Jacques Prévert]"),
        new fmrCitation("Pour connaître l'âge d'une femme, il faut la voir avant son petit déjeuner. [Jacques Dutronc]"),
        new fmrCitation("L'argent est une richesse morte, les enfants sont une richesse vivante. [Proverbe chinois]"),
        new fmrCitation("Une mauvaise vie vaut mieux qu'une belle mort. [Proverbe chinois]"),
        new fmrCitation("Fais n'importe quoi, mais tires-en de la joie. [Henry Miller]"),
        new fmrCitation("Le bonheur, c'est tout ce qui arrive entre deux emmerdements... [Jean-Baptiste Lafond]"),
        new fmrCitation("L'entreprise ne peut exiger la loyauté de ses salariés : elle doit la mériter. [Charles Handy]"),
        new fmrCitation("Tous les paramètres sont nominaux; on est opérationnels phase par phase. [Vasquez dans Aliens de James Cameron]"),
        new fmrCitation("Les grands travailleurs ne valent rien pour les grandes places ; mais ils sont bons pour les emplois subalternes. [Duc de Lévis]"),
        new fmrCitation("Le peuple est le même partout. Quand on dore ses fers, il ne hait pas la servitude. [Napoléon Bonaparte]"),
        new fmrCitation("Il faut collectionner  les pierres qu'on vous jette. C'est le début d'un piédestal. [Hector Berlioz]"),
        new fmrCitation("Si deux hommes sont d'accord sur tout, c'est qu'un seul des deux pense. [Lyndon Johnson]"),
        new fmrCitation("Ceux qui aperçoivent la lumière avant les autres sont condamnés à la poursuivre en dépit des autres. [Christophe Colomb]"),
        new fmrCitation("Les hommes construisent trop de murs et pas assez de ponts. [Isaac Newton]"),
        new fmrCitation("Sans technique, le talent n'est rien qu'une sale manie. [Georges Brassens]"),
        new fmrCitation("Je ne remercierai jamais assez Bill Gates pour avoir transformé un métier relativement terne et basé sur une approche bêtement technique et rigoureuse des faits, en challenge quotidien, nécessitant une remise en question permanente à l'échelle du quart d'heure. [Roberto Di Cosmo]"),
        new fmrCitation("Savoir pour prévoir, afin de pouvoir. [Auguste Comte]"),
        new fmrCitation("On ne va jamais si loin que lorsque l'on ne sait pas où l'on va. [Rivarol]"),
        new fmrCitation("On peut feindre d'avoir du cœur, pas d'avoir de l'esprit. [Paul Morand]"),
        new fmrCitation("On devient son pire ennemi en essayant de donner du sens à ce qui n'en a pas. [Hubert Selby Junior]"),
        new fmrCitation("L'oisiveté est, dit-on, la mère de tous les vices, mais l'excès de travail est le père de toutes les soumissions. [Albert Jacquard]"),
        new fmrCitation("Le luxe n'est pas un plaisir, mais le plaisir est un luxe. [Francis Picabia]"),
        new fmrCitation("Ce qui m'intéresse, ce n'est pas le bonheur de tous les hommes, c'est celui de chacun. [Boris Vian]"),
        new fmrCitation("Ce qu'on n'a jamais mis en question n'a point été prouvé. [Denis Diderot]"),
        new fmrCitation("C'est le propre de l'homme de se tromper ; seul l'insensé persiste dans son erreur. [Cicéron]"),
        new fmrCitation("Un grand voyage commence toujours par un petit pas. [Proverbe Bouddhiste]"),
        new fmrCitation("Ainsi qu'une mère au péril de sa vie surveille et protège son unique enfant, Ainsi avec un esprit sans limite doit-on chérir toute chose vivante. [Bouddha]"),
        new fmrCitation("Si vous avez souffert, c'est juste que vous avez oublié que vous êtes une fleur, une feuille. [Thich Nhat Hanh]"),
        new fmrCitation("Notre joie ne peut survivre sans nourriture; notre tristesse non plus, notre désespoir non plus, rien ne peut survivre sans nourriture. [Thich Nhat Hanh]"),
        new fmrCitation("Tous les phénomènes qui apparaissent en interdépendance, je dis qu'ils sont vides. Les mots cessent, parce que leur message est faux. [Nagarjuna] "),
        new fmrCitation("Quand entre soi et autrui il n'y a plus aucune distinction, comment y aurait-il alors Connaissance-en-soi et autre connaissance? [Brugpa Kun legs]"),
        new fmrCitation("La pensée du néant des choses engendre la compassion, La compassion abolit l'espace entre soi et les autres, L'unité de soi et des autres réalise le bien d'autrui . [Milarepa]"),
        new fmrCitation("Prétendre être inférieur à l'inférieur, Égal à l'égal, Supérieur ou égal à l'inférieur, Cela est dit orgueil. [Nagarjuna]"),
        new fmrCitation("C'est parce que l'on fait un choix, Que sa vérité absolue se trouve perdue de vue.  [Sengtsan] "),
        new fmrCitation("Toutes les choses dans ce monde se résolvent dans la Vacuité, elles ne viennent pas à l'être, elles ne cessent pas d'être, elles ne sont ni altérées, ni immaculées, elles n'augmentent ni ne diminuent.  [Bouddha]"),
        new fmrCitation("C'est moi, c'est un autre, concoit-on. Dépouille ce lien qui rend captif, c'est ainsi qu'on se libère soi-même.  [Saraha] "),
        new fmrCitation("Le bruit du tonnerre est terrible mais sans substance, les couleurs de l'arc en ciel ravissantes mais ephemères. Ce monde plaisant à l'esprit n'est pourtant qu'un rêve.  [Milarepa] "),
        new fmrCitation("Tout ce qui est produit en dépendance ne peut être indépendant. Et comme tout est non-indépendant, il n'y a pas de soi.  [Aryadeva]"),
        new fmrCitation("Tous les phénomènes sont projection de l'esprit, quand à l'esprit, il n'est pas d'esprit. l'esprit est vide d'essence.  [Karmapa III]"),
        new fmrCitation("Sans l'experience de ce qu'elles sont, mes propres projections m'illusionnent comme objets. Dans l'ignorance, l'intelligence autoconnaissant développe l'illusion d'un sujet.  [Karmapa III]"),
        new fmrCitation("La nature de tout phénomène, de toute apparence, est semblable au reflet de la lune sur l'eau.  [Bouddha]"),
        new fmrCitation("Considerer le monde comme réel est attitude animale; le considerer comme vide est bien plus bête.  [Saraha]"),
        new fmrCitation("Ne cherchez pas le passé, ne cherchez pas le futur; le passé est evanoui, le futur n'est pas encore advenu. Mais observez ici cet objet qui est maintenant.  [Bouddha]"),
        new fmrCitation("Tous les composés sont impermanents. Quand vous percevez cela par l'intuition vraie alors, vous vous détachez de la souffrance.  [Bouddha]"),
        new fmrCitation("Sans fin et sans naissance, ni néant ni eternité, Cela ne vient ni ne s'en va et n'est ni Un ni multiple.  [Bouddha]"),
        new fmrCitation("Quand il y a soi il y a conscience de l'autre. Du soi et de l'autre naissent attachement et répulsion, et de la combinaison des deux proviennent tous les maux.  [Dharmakirti]"),
        new fmrCitation("Comme dans un miroir parfaitement pur apparaissent d'insubstantiels reflets, sache qu'il en est ainsi pour toute chose.  [Bouddha]"),
        new fmrCitation("Jamais la haine n'éteint les haines en ce monde. Par l'amour seul les haines sont éteintes. C'est une loi eternelle.  [Bouddha]"),
        new fmrCitation("S'il y a un remède, à quoi bon le mécontentement? S'il n'y a pas de remède, à quoi bon le mécontentement?  [Shantideva]"),
        new fmrCitation("Ne poursuivez pas l'objet de votre haine, regardez votre esprit en colère : la colère en naissant se libère, claire et vide.  [Patrul Rinpotche]"),
        new fmrCitation("Tout ce que vous percevez est méprise et n'existe pas vraiment. Le samsara et le Nirvana ne sont que des idées.  [Patrul Rinpotche]"),
        new fmrCitation("Pour l'amoureux, une jolie femme est un objet de réjouissance; pour l'ermite, un sujet de distraction; pour le loup, un bon repas.  [Adage bouddhiste]"),
        new fmrCitation("L'essence de la réalité est mouvement.  [Shantarakshita]"),
        new fmrCitation("Ne rejette pas les apparences car elles sont le rayonnement de l'esprit lui-même.  [Gampopa]"),
        new fmrCitation("Ne te consacre pas à l'ascèse dans la forêt, la joie n'est pas obtenue par les ablutions et la pureté exterieure (...) Connais, complètement ouvert, sans acceptation ni rejet.  [Tilopa]"),
        new fmrCitation("L'homme compatissant est bon, même en colère; dénué de compassion il tue avec le sourire.  [Shabkar]"),
        new fmrCitation("Qui a la compassion possède tous les enseignements, qui ne l'a pas n'en possède aucun.  [Shabkar]"),
        new fmrCitation("Si vous pensez que tout est parfait dans votre vie, soit vous êtes un Bouddha, soit vous êtes complètement idiot.  [Proverbe tibetain]"),
        new fmrCitation("Si avec un mental impur, quelqu'un parle ou agit, alors la douleur le suit d'aussi près que la roue qui suit le sabot du boeuf.  [Dhammapada]"),
        new fmrCitation("Par l'effort, l'ardeur, la discipline et le contrôle, que le sage fasse pour lui même une île qu' aucun flot ne pourra submerger.  [Dhammapada]"),
        new fmrCitation("Santal, tagara, lotus, jasmin, de tous ces parfums le parfum de l'éthique est de loin le meilleur.  [Dhammapada]"),
        new fmrCitation("Meilleur que mille mots sans utilité, est un seul mot bénéfique, qui pacifie celui qui l'entend.  [Dhammapada]"),
        new fmrCitation("S'abstenir de tout mal, cultiver le bien, purifier son coeur, voici l'enseignement des Bouddhas.  [Dhammapada]"),
        new fmrCitation("La victoire engendre la haine, le vaincu vit dans la souffrance. Le paisible vit heureux, abandonnant victoire et défaite.  [Dhammapada]"),
        new fmrCitation("L'arbre qui tombe dans la forêt fait-il du bruit si personne ne l'entend ?  [Koan zen]"),
        new fmrCitation("Quel était votre visage avant votre naissance ?  [Koan zen]"),
        new fmrCitation("Ne dites pas que la lune existe lorsque les nuages s'en vont; Elle a toujours été là parfaitement claire.  [Zenkei Shibayama]"),
        new fmrCitation("Frappe le ciel et écoute le bruit.  [Koan zen]"),
        new fmrCitation("J'écoute le chant de l'oiseau non pour sa voix, mais pour le silence qui la suit.  [Noguchi Yonenro]"),
        new fmrCitation("Qui donc est celui que j'ai en face de moi ? Je l'ignore.  [Bodhidharma]"),
        new fmrCitation("Ne vous fiez pas à ce qui a été acquis du fait de l'avoir entendu de façon répétée; ni du fait de la tradition; ni du fait de la rumeur; ni du fait que ça se trouve dans une écriture...  [Bouddha]"),
        new fmrCitation("L'amour bienveillant peut être développé envers une personne qui vous irrite: c'est ainsi que l'agacement peut être surmonté.  [Bouddha]"),
        new fmrCitation("La compassion peut être développée envers une personne qui vous irrite: c'est ainsi que l'agacement peut également être surmonté.  [Bouddha]"),
        new fmrCitation("L'équanimité peut être développée envers une personne qui vous irrite: c'est ainsi que l'agacement peut également être surmonté.  [Bouddha]"),
        new fmrCitation("Il n'y a pas (...) de lumière plus grande que celle de la sagesse.  [Bouddha]"),
        new fmrCitation("Il n'y a pas (...) de lac plus grand que la pluie.  [Bouddha]"),
        new fmrCitation("C'est par le désir que le monde est lié. Par l'assujettissement du désir qu'il est libéré.  [Bouddha]"),
        new fmrCitation("C'est ayant tué la colère qu'on peut dormir en paix.  [Bouddha]"),
        new fmrCitation("La forme est comme une boule d'écume ;la sensation, une bulle; la perception, un mirage; les volitions, un bananier; la conscience, un tour de magie.  [Bouddha]"),
        new fmrCitation("Tout ce qui est qui surgit dépendamment du contact avec l'intellect, qui est ressenti en tant que plaisir, douleur ou avec indifférence, cela aussi se désintègre.  [Bouddha]"),
        new fmrCitation("Strictement parlant, la durée de la vie d'un être ne dépasse pas la durée d'une pensée  [Inconnu]."),
        new fmrCitation("L'esprit qui médite sur l'apparition et la disparition, qui considère l'impermanence du monde, on le nomme esprit d'Eveil.  [Nagarjuna]"),
        new fmrCitation("Le temps présent est semblable à la boule d'argile, le temps passé à la poussière de la terre, et le temps futur à la cruche.  [Nagarjuna]"),
        new fmrCitation("Le nirvana n'est pas inexistence. D'où viendrait alors qu'on le réalise ? Est appelé nirvana la cessation de toute prise de conscience quant à être et non-être ?  [Nagarjuna]"),
        new fmrCitation("Le sage connaît directement la coproduction interdépendante (...) il sait que les choses ont des causes, dépendent de circonstances, et que rien n'existe sans cause ni circonstances.  [Bouddha]"),
        new fmrCitation("Ce qui apparaît en fonction d'autre chose n'est en rien cette chose, mais n'en est pas non plus différent. Ainsi cela n'est il ni eternel ni néant.  [Nagarjuna]"),
        new fmrCitation("I n'y a ni tableau dans l'esprit, ni esprit dans le tableau ; et pourtant, peut on trouver un tableau hors de l'esprit.  [Bouddha]"),
        new fmrCitation("Comme l'étoile filante, le mirage, la flamme, l'illusion magique, la goutte de rosée, la bulle sur l'eau ; comme le rêve l'éclair ou le nuage : Considère ainsi toutes choses.  [Bouddha]"),
        new fmrCitation("Tout le bonheur du monde vient d'un coeur altruiste, et tous son malheur de l'amour de soi.  [Shantideva]"),
        new fmrCitation("Bien que mes ennemis,la haine,l'attachement et ainsi de suite,n'ont ni armes ni bras ni jambes,ils me font quand même du mal,me torturent et me traitent comme un esclave.  [Shantideva]"),
        new fmrCitation("Le nirvâna, c'est l'abandon de tout ; et mon âme aspire au nirvâna. Puisque je dois tout abandonner, le mieux est de le donner  [Shantideva]"),
        new fmrCitation("Que je ne sois pour personne l'occasion d'aucun dommage ! Si leur cœur est irrité et malveillant à mon sujet, que cela même serve à réaliser les fins de tous !  [Shantideva]"),
        new fmrCitation("Les Bouddhas parlent de la vacuité afin de détruire les vues fausses. Mais si vous vous attachez à la vacuité, les bouddhas eux-mêmes ne peuvent plus rien pour vous  [Bodhidharma]"),
        new fmrCitation("Chercher le Bouddha en rejetant les êtres est comme chercher l'écho en faisant taire la voix.  [Bodhidharma]"),
        new fmrCitation("La boudheité (...) est comme le ciel : bien qu'elle se pare d'innombrables mérites et formes de sagesse, rien de tout cela n'y est fixé.  [Houang Po]"),
        new fmrCitation("Quand on n'a plus besoin de se croire quelqu'un, c'est ça que j'aime (...) Quand on a renoncé à tromper les êtres vivants, Il n'y a plus d'action, et pourtant tout se fait...  [Kun Legs]"),
        new fmrCitation("Moi, le moine de montagne, je n'ai aucune Loi à donner, je ne fais que dénouer des liens.  [Lin Tsi]"),
        new fmrCitation("Sortir du Triple Monde, imbéciles ! Pour aller où ? Le Bouddha et les patriarches, ce ne sont que des noms dont on prend plaisir à se laisser lier.  [Lin Tsi]"),
        new fmrCitation("Si vous rencontrez un Bouddha, tuez-le ! Si vous rencontrez un patriarche, tuez-le ! Si vous rencontrez un arhat, tuez-le !  [Lin Tsi]"),
        new fmrCitation("Le vrai Bouddha est sans figure, la vraie Loi est sans marques... quant au véritable apprenti du Chemin, il ne s'attache pas au Bouddha, ni aux bodhisattva, ni aux arhat  [Lin Tsi]"),
        new fmrCitation("Chercher le Bouddha, c'est perdre le Bouddha ; chercher les patriarches, c'est perdre les patriarches ; chercher la Voie, c'est perdre la Voie... Tout ce qu'il faut c'est avoir la vue juste  [Lin Tsi]"),
        new fmrCitation("Le recueillement d'Avalokiteshvara, c'est votre propre esprit capable en chacune de ses pensées de se défaire de ses liens et de se libérer point par point.  [Lin Tsi]"),
        new fmrCitation("Sachant que les possessions sont éphémères et dénuées d'essence, Pratique avec respect la générosité  [Nagarjuna]"),
        new fmrCitation("Il n'existe aucune faute comparable à la colère, Et pas de courage comparable à la patience  [Nagarjuna]"),
        new fmrCitation("Sache que l'esprit est semblable à un dessin tracé sur l'eau, la terre ou dans la pierre. Chez les personnes agitées la première image est la meilleure, pour celles aspirant au spirituel, c'est la dernière.  [Nagarjuna]"),
        new fmrCitation("Sois toujours satisfait car celui qui connaît la satisfaction, même s'il ne possède rien est véritablement riche  [Nagarjuna]"),
        new fmrCitation("Le corps est heureux par la vertu, le coeur par la sagesse.  [Shantideva]"),
        new fmrCitation("Lorsque tu compasses le monde avec ta parfaite intelligence et compassion, il doit te sembler être un rêve dont on ne peut dire : il est permanent ou il est destructible, car l'être et le non-être ne s'appliquent pas à lui  [Lankavatara soutra]"),
        new fmrCitation("Tu ne disparais pas dans le Nirvâna, et le Nirvâna ne se trouve pas en toi, car le Nirvâna transcende toute dualité du connaissant et du connu, de l'être et du non-être.  [Lankavatara soutra]"),
        new fmrCitation("L'erreur de ces enseignements erronés que tiennent généralement les philosophes tient en ceci : ils ne reconnaissent pas que le monde objectif surgit de l'esprit lui-même  [Lankavatara soutra]"),
        new fmrCitation("Les mots et les phrases sont produits par la loi de causalité et se conditionnent mutuellement : ils ne peuvent pas exprimer la Réalité ultime.  [Lankavatara soutra]"),
        new fmrCitation("Tant que les gens ne comprennent pas la véritable nature du monde objectif, ils tombent dans une vision dualiste  [Lankavatara soutra]"),
        new fmrCitation("L'erreur n'a pas en elle de caractère qui entraîne l'attachement; si l'erreur avait un tel caractère, aucune libération ne serait possible de son attachement à l'existence.  [Lankavatara soutra]"),
        new fmrCitation("Ces enseignements ne sont qu'un doigt pointé vers la Noble Sagesse.  [Lankavatara soutra]"),
        new fmrCitation("Les soutras sont prévus pour la considération et la guidance de l'esprit discriminant de tout le monde, mais ils ne sont pas la Vérité elle-même.  [Lankavatara soutra]"),
        new fmrCitation("La destruction de tous les liens, c'est le Nirvâna  [Bouddha]"),
        new fmrCitation("Que je sois libéré de la colère, d'états mentaux malsains, de la peur et des soucis.  [Thich Nhat Hanh]"),
        new fmrCitation("Que je sois capable d'identifier et de voir l'origine de la colère, du désir et de l'illusion en moi-même.  [Thich Nhat Hanh]"),
        new fmrCitation("Que j'apprenne à me nourrir de Joie chaque jour. Que je sois capable de vivre dans la fraîcheur, la solidité et la Liberté.  [Thich Nhat Hanh]"),
        new fmrCitation("Que je ne tombe pas dans un état d'indifférence et ne sois pas pris par les souffrances de l'attachement et de l'aversion.  [Thich Nhat Hanh]"),
        new fmrCitation("Le Bonheur ne se trouve pas avec beaucoup d'effort et de volonté, mais réside là, tout près, dans la détente et l'abandon  [Guendune Rimpoche]"),
        new fmrCitation("Ne t'inquiète pas, il n'y a rien à faire. Tout ce qui s'élève dans l'esprit n'a aucune importance parce que n'a aucune réalité.  [Guendune Rimpoche]"),
        new fmrCitation("Laisse le jeu se faire tout seul, s'élever et retomber, sans rien changer, et tout s'évanouit et recommence à nouveau, sans cesse.  [Guendune Rimpoche]"),
        new fmrCitation("Ne crois pas à la réalité des expériences bonnes ou mauvaises, elles sont comme des arc-en-ciel. A vouloir l'insaisissable, on s'épuise en vain.  [Guendune Rimpoche]"),
        new fmrCitation("Dès lors qu'on relâche cette saisie, l'espace est là, ouvert, hospitalier et confortable. Alors, profites-en. Tout est à toi, déjà.  [Guendune Rimpoche]"),
        new fmrCitation("Lorsqu'on est libre de toute intention, et ne demeure sur aucune conclusion, tous dharma et enseignements sont vus.  [Tilopa]"),
        new fmrCitation("Le meilleur moyen de prendre un train à l'heure, c'est de s'arranger pour rater le précédent. [Marcel Achard]"),
        new fmrCitation("L'oubli de ses propres fautes est la plus sure des absolutions. [Konrad Adenauer]"),
        new fmrCitation("L'argent aide a supporter la pauvreté. [Alphonse Allais]"),
        new fmrCitation("Il est très curieux de constater que dans l'armée, les statistiques le prouvent, la mortalité augmente bizarrement en temps de guerre. [Alphonse Allais]"),
        new fmrCitation("Une auto-stoppeuse est une jeune femme généralement jolie et court vêtue qui se trouve sur votre route quand vous êtes avec votre femme. [Woody Allen]"),
        new fmrCitation("Si Dieu avait voulu que l'on prit la Vie sérieusement, il ne nous aurait pas donné le sens de l'humour. [Anonyme]"),
        new fmrCitation("Il faut battre son frère quand il est chaud. [Honoré de Balzac]"),
        new fmrCitation("Avant de choisir le prénom d'un garçon, pensez toujours a la femme qui aura a le murmurer plus tard. [Barbey d'Aurevilly]"),
        new fmrCitation("Les hommes sont toujours sincères Ils changent de sincérité, voilà tout. [Tristan Bernard]"),
        new fmrCitation("Avec les femmes, il faudrait que les paroles soient d'autant plus respectueuses que les gestes le deviennent de moins en moins. [Tristan Bernard]"),
        new fmrCitation("On ne prête qu'aux riches, et on a bien raison, parce que les autres remboursent difficilement. [Tristan Bernard]"),
        new fmrCitation("Il ne faut compter que sur soi-même Et encore, pas beaucoup. [Tristan Bernard]"),
        new fmrCitation("Le comble de l'optimisme, c'est de rentrer dans un grand restaurant et compter sur la perle qu'on trouvera dans une huître pour payer la note. [Tristan Bernard]"),
        new fmrCitation("A vingt ans, l'enfant déforme la femme; a trente ans, il la conserve, a quarante ans, je crois bien qu'il la rajeunit. [Léon Blum]"),
        new fmrCitation("L'argent, c'est comme les femmes, pour le garder, il faut s'en occuper, sans cela il va faire le bonheur de quelqu'un d'autre. [Edouard Bourdet]"),
        new fmrCitation("Il faut choisir, dans la vie, entre gagner de l'argent et le dépenser; on n'a pas le temps de faire les deux. [Edouard Bourdet]"),
        new fmrCitation("Il y a des femmes qui n'aiment pas faire souffrir plusieurs hommes a la fois, qui préfèrent s'appliquer a un seul: ce sont les femmes fidèles. [Alfred Capus]"),
        new fmrCitation("Ce qui est grave dans un ménage, c'est quand l'un aime et l'autre pas.| Mais s'ils ne s'aiment ni l'un ni l'autre, ils peuvent être très heureux. [Alfred Capus]"),
        new fmrCitation("A Paris, ce qu'on appelait autrefois l'âge mur tend a disparaître On reste très jeune très longtemps, puis on devient gâteux. [Alfred Capus]"),
        new fmrCitation("Si j'avais encore l'argent que j'ai dépensé pour boire, qu'est-ce que je pourrais me payer comme apéritifs!. [Celmas]"),
        new fmrCitation("Il y a des femmes qui trouvent a se vendre et qui ne trouveraient pas a se donner. [Chamfort]"),
        new fmrCitation("La société est divisée en deux classes: ceux qui ont plus de dîners que d'appétit et ceux qui ont plus d'appétit que de dîners. [Chamfort]"),
        new fmrCitation("Apprendre a mourir ! Et pourquoi donc? On y réussit très bien la première fois!. [Chamfort]"),
        new fmrCitation("C'est très curieux : ce sont toujours les célibataires qui vous donnent des conseils pour élever des enfants. [Paul Claudel]"),
        new fmrCitation("De tous les plaisirs, quand il n'en reste plus, il reste toujours celui de se lever de table après un repas ennuyeux. [Paul Claudel]"),
        new fmrCitation("Quatre-vingt ans, c'est l'âge de la puberté académique. [Paul Claudel]"),
        new fmrCitation("On ne ment jamais autant qu'avant les élections, pendant la guerre et après la chasse. [Georges Clemenceau]"),
        new fmrCitation("La guerre, c'est une chose trop grave pour la confier a des militaires. [Georges Clemenceau]"),
        new fmrCitation("Un traître est un homme politique qui quitte son parti pour s'inscrire a un autre. Par contre, un converti est un homme politique qui quitte son parti pour s'inscrire au votre. [Georges Clemenceau]"),
        new fmrCitation("Les fonctionnaires sont un petit peu comme les livres d'une bibliothèque. Ce sont les plus hauts placés qui servent le moins. [Georges Clemenceau]"),
        new fmrCitation("Les miroirs feraient bien de réfléchir avant de renvoyer les images. [Jean Cocteau]"),
        new fmrCitation("Un enfant prodige, c'est un enfant dont les parents ont beaucoup d'imagination. [Jean Cocteau]"),
        new fmrCitation("L'homme n'est pas fait pour travailler.  La preuve, c'est que ca le fatigue. [Georges Courteline]"),
        new fmrCitation("La femme ne voit jamais ce que l'on fait pour elle; elle ne voit que ce que l'on ne fait pas. [Georges Courteline]"),
        new fmrCitation("Lorsque ma femme me fait un cadeau, j'ai deux surprises: d'abord le cadeau, ensuite de le payer. [Maurice Donnay]"),
        new fmrCitation("Les chaînes du mariage sont si lourdes qu'il faut être deux pour les porter;  quelquefois trois. [Alexandre Dumas]"),
        new fmrCitation("On a le droit de dire du mal des femmes; on n'a pas le droit de dire le mal d'une femme. [Alexandre Dumas]"),
        new fmrCitation("Le mariage, c'est l'art pour deux personnes de vivre ensemble aussi heureuses qu'elles auraient vécu chacune de leur cote. [Georges Feydau]"),
        new fmrCitation("Quand un philosophe vous répond, on ne comprend même plus ce qu'on lui avait demande. [André Gide]"),
        new fmrCitation("L'égoïste est celui qui n'emploie pas toutes les minutes de sa vie a assurer le bonheur de tous les autres égoïstes. [Lucien Guitry]"),
        new fmrCitation("La réussite, pour un homme, c'est d'être parvenu a gagner plus d'argent que sa femme n'a pu en dépenser. [Sacha Guitry]"),
        new fmrCitation("A l'égard de quelqu'un qui vous prend votre femme, la pire vengeance est de la lui laisser. [Sacha Guitry]"),
        new fmrCitation("Certains hommes n'ont que ce qu'ils méritent; les autres sont célibataires. [Sacha Guitry]"),
        new fmrCitation("Tous les hommes naissent comédiens, sauf quelques acteurs. [Sacha Guitry]"),
        new fmrCitation("Il ne faut jamais regarder quelqu'un qui dort. C'est comme si on ouvrait une lettre qui ne vous est pas adressée. [Sacha Guitry]"),
        new fmrCitation("Il n'y a pas de bonheur parfait dit l'homme quand sa belle-mère mourut et qu'on lui présenta la note des pompes funèbres. [Jerome K. Jerome]"),
        new fmrCitation("Quand on vient au monde, on est tous de la même couleur: violette. [Yvon Deschamps]"),
        new fmrCitation("Un soldat doit être prêt a mourir pour sa patrie, même au péril de sa vie. [Henri Monnier]"),
        new fmrCitation("Si haut que l'on soit placé, on n'est jamais assis que sur son cul. [Montaigne]"),
        new fmrCitation("Les curés se consolent de n'être pas mariés quand ils entendent les femmes se confesser. [Armand Salacroix]"),
        new fmrCitation("Que l'on meurt gros ou maigre, la différence, c'est pour les porteurs. [Peter Ustinov]"),
        new fmrCitation("Dieu créa l'homme et, ne le trouvant pas assez seul, il lui donna une compagne pour lui faire mieux sentir sa solitude. [Paul Valery]"),
        new fmrCitation("Il ne faut jamais juger les gens sur leurs fréquentations: Judas, par exemple, avait des amis irréprochables. [Verlaine]"),
        new fmrCitation("Si Dieu nous a faits a son image, nous lui avons bien rendu. [Voltaire]"),
        new fmrCitation("J'ai souvent remarqué, pour ma part, que les cocus épousent de préférence les femmes adultères. [Alphonse Allais]"),
        new fmrCitation("Le meilleur moyen de faire tourner la tête à une femme, c'est de lui dire qu'elle a un joli profil. [Sacha Guitry]"),
        new fmrCitation("Il y a des femmes dont l'infidélité est le seul lien qui les attache encore à leur mari. [Sacha Guitry]"),
        new fmrCitation("Expérience: nom dont les hommes baptisent leurs erreurs. [Oscar Wilde]"),
        new fmrCitation("J'aime les hommes qui ont de l'avenir et les femmes qui ont un passé. [Oscar Wilde]"),
        new fmrCitation("La dictature, c'est  ferme ta gueule , et la démocratie, c'est  cause toujours . [Woody Allen]"),
        new fmrCitation("Les champignons poussent dans les endroits humides. C'est pourquoi ils ont la forme d'un parapluie. [Alphonse Allais]"),
        new fmrCitation("Il y a deux ans que je n'ai pas parlé à ma femme, c'était pour ne pas l'interrompre. [Jules Renard]"),
        new fmrCitation("Ma femme et moi avons été heureux vingt-cinq ans; et puis, nous nous sommes rencontrés. [Sacha Guitry]"),
        new fmrCitation("C'est parce que la fortune vient en dormant que celle-ci arrive si lentement. [Alphonse Allais]"),
        new fmrCitation("C'est quand on serre une femme de trop près qu'elle trouve qu'on va trop loin. [Alphonse Allais]"),
        new fmrCitation("Quand on ne travaillera plus les lendemains des jours de repos, la fatigue sera vaincue. [Alphonse Allais]"),
        new fmrCitation("Fais confiance à Dieu, mais ferme ta voiture à clé. [Anonyme]"),
        new fmrCitation("La politique est l'art d'obtenir de l'argent des riches et des suffrages des pauvres, sous prétexte de les protéger les uns des autres. [Anonyme]"),
        new fmrCitation("Quelle prétention de prétendre que l'informatique est récente: Adam et Eve avaient déjà un Apple!. [Anonyme]"),
        new fmrCitation("La célébrité m'a apporté un gros avantage: les femmes qui me disent non sont plus belles qu'autrefois. [Woody Allen]"),
        new fmrCitation("Si je fais si bien l'amour, c'est que je me suis longtemps entraîné tout seul. [Woody Allen]"),
        new fmrCitation("Un conducteur dangereux, c'est celui qui vous dépasse malgré tous vos efforts pour l'en empêcher. [Woody Allen]"),
        new fmrCitation("L'argent est plus utile que la pauvreté, ne serait-ce que pour des questions financières. [Woody Allen]"),
        new fmrCitation("Elles croient que tous les hommes sont pareils, parce qu'elles se conduisent de la même manière avec tous les hommes. [Sacha Guitry]"),
        new fmrCitation("Si le plus grand plaisir des hommes est de se payer les corps des femmes, le plus grand plaisir des femmes est de se payer la tête des hommes. [Sacha Guitry]"),
        new fmrCitation("La moitié des hommes politiques sont des bons à rien.  Les autres sont prêts à tout. [Coluche]"),
        new fmrCitation("Il ne faut jamais faire de projets, surtout en ce qui concerne l'avenir. [Alphonse Allais]"),
        new fmrCitation("Un imprimeur est un homme qui ne manque pas de caractère et qui cherche à faire bonne impression. [Serge Mirjean]"),
        new fmrCitation("Il est préférable d'avoir de très gros défauts que de toutes petites qualités. [Frédéric Dard]"),
        new fmrCitation("Je n'ai pas assisté à beaucoup de courses de spermatozoïdes mais j'ai donné beaucoup de départs. [Olivier de Kersauson]"),
        new fmrCitation("Il ne faut pas désespérer des imbéciles. Avec un peu d'entraînement, on peut arriver à en faire des militaires. [Pierre Desproges]"),
        new fmrCitation("Dieu a dit:  Il faut partager . Les riches auront la nourriture, les pauvres de l'appétit. [Coluche]"),
        new fmrCitation("Il est faux que les femmes frigides vivent plus longtemps que les autres. Simplement, le temps leur semble plus long. [François Cavanna]"),
        new fmrCitation("En fait l'important ne serait pas de réussir sa vie, mais de rater sa mort. [Jean Yanne]"),
        new fmrCitation("Il faut faire des enfants quand on est vieux, parce qu'on les emmerde pas longtemps. [Jean Yanne]"),
        new fmrCitation("L'amour c'est un sport. Surtout s'il y en a un des deux qui veut pas. [Jean Yanne]"),
        new fmrCitation("Pour le pape, le plus dur c'est de ne pas avoir d'homologue avec qui causer boulot. [Jean Yanne]"),
        new fmrCitation("La dernière fois que j'ai pénétré une femme, c'était en visitant la statue de la Liberté. [Woody Allen]"),
        new fmrCitation("Au commencement, Dieu ne savait pas qu'il était Dieu, puisqu'il était tout seul. Pour savoir qu'on est Dieu, il faut être deux: un qui est Dieu, et l'autre qui lui dit: «Mon Dieu». [François Cavanna]"),
        new fmrCitation("Votre enfant devient adolescent lorsqu'il cesse de demander d'où il vient et qu'il ne dit plus où il va. [Anonyme]"),
        new fmrCitation("Se marier, c'est partager à deux les problèmes que l'on n'aurait pas eu tout seul. [Anonyme]"),
        new fmrCitation("Ce n'est pas en tournant le dos aux choses qu'on leur fait face. [Pierre Dac]"),
        new fmrCitation("On croit souvent qu'un appartement est bas de plafond, alors qu'il est tout simplement haut de plancher. [Pierre Dac]"),
        new fmrCitation("On dit d'un accusé qu'il est cuit quand son avocat n'est pas cru. [Pierre Dac]"),
        new fmrCitation("Si on portait ses chaussures à la main plutôt qu'aux pieds, elles s'useraient moins vite. [Pierre Dac]"),
        new fmrCitation("Après l'amour, dix pour cent des hommes se retournent sur leur côté droit et s'endorment, dix pour cent font de même sur le côté gauche. Les autres se rhabillent et rentrent chez eux. [Francis Blanche]"),
        new fmrCitation("Comme l'amour est aveugle, il est très important de toucher. [Proverbe Brésilien]"),
        new fmrCitation("Trois sortes d'hommes ne comprennent rien aux femmes: les jeunes, les vieux et ceux entre les deux. [Proverbe Irlandais]"),
        new fmrCitation("Il est plus dangereux de tomber en amour que de tomber du haut d'une falaise. [Plaute]"),
        new fmrCitation("On a d'abord les femmes dans ses bras, puis un jour sur les bras, et bientôt sur le dos. [Sacha Guitry]"),
        new fmrCitation("Plus le coeur est petit, plus la langue est longue. [Proverbe Italien]"),
        new fmrCitation("L'amour c'est comme le potage, les premières cuillerées sont trop chaudes, les dernières trop froides. [Jeanne Moreau]"),
        new fmrCitation("L'amour est aveugle, mais le mariage lui rend la vue. [Proverbe Allemand]"),
        new fmrCitation("La célébrité m'apporte beaucoup. Les femmes qui me disent non sont beaucoup plus belles qu'avant. [Woody Allen]"),
        new fmrCitation("Un diplomate, c'est un homme qui se souvient toujours de l'anniversaire d'une femme, mais qui ne se souvient jamais de son âge. [Proverbe Américain]"),
        new fmrCitation("Une heure assis à côté d'une jolie femme semble durer une minute. Une minute assis sur un four brûlant semble durer une heure. C'est ça la relativité. [Albert Einstein]"),
        new fmrCitation("Le mariage est la seule condamnation à vie qui peut être suspendue pour mauvaise conduite. [Oscar Wilde]"),
        new fmrCitation("Le mariage, c'est une période de repos entre deux passions. [Elisabeth Taylor]"),
        new fmrCitation("Ne faites jamais l'amour le samedi soir, car, s'il pleut le dimanche,vous ne saurez plus quoi faire. [Sacha Guitry]"),
        new fmrCitation("Le mariage n'est pas une loterie. À la loterie il y a des gagnants. [George Bernard Shaw]"),
        new fmrCitation("La moitié des hommes sont des salauds, et l'autre moitié est horriblement ennuyante. [Joan Collins]"),
        new fmrCitation("Le divorce est une maladie qui s'attrape par le mariage. [Elisabeth Taylor]"),
        new fmrCitation("Les hommes se marient par fatigue, les femmes par curiosité; les deux sont déçus. [Oscar Wilde]"),
        new fmrCitation("Les amours, c'est comme les champignons, il est trop tard quand on découvre qu'ils sont empoissonnés. [Tristan Bernard]"),
        new fmrCitation("Les hommes aiment la profondeur chez les femmes, mais seulement dans leur décolleté. [Mae West]"),
        new fmrCitation("La seule tâche ménagère que la plupart des couples partagent, c'est le lavage du linge sale en famille. [Confucius]"),
        new fmrCitation("Le verbe  aimer  est le plus compliqué de la langue. Son passé n'est jamais simple, son présent n'est qu'imparfait et son futur toujours conditionnel. [Jean Cocteau]"),
        new fmrCitation("Si vous êtes pauvre, ne sortez pas avec une végétarienne, elle risque de vous quitter pour une grosse légume. [Confucius]"),
        new fmrCitation("Les femmes partagent nos plaisirs, doublent nos tourments et triplent nos dépenses. [Oscar Wilde]"),
        new fmrCitation("On ne prête qu'aux riches, et on a bien raison, parce que les autres remboursent difficilement. [Tristan Bernard]"),
        new fmrCitation("Il ne faut compter que sur soi-même. Et encore, pas beaucoup. [Tristan Bernard ]"),
        new fmrCitation("Le comble de l'optimisme, c'est de rentrer dans un grand restaurant et compter sur la perle qu'on trouvera dans une huître pour payer la note. [Tristan Bernard]"),
        new fmrCitation("A vingt ans, l'enfant déforme la femme; a trente ans,il la conserve, a quarante ans, je crois bien qu'il la rajeunit ! [Léon Blum]"),
        new fmrCitation("L'argent, c'est comme les femmes, pour le garder, il faut s'en occuper, sans cela il va faire le bonheur de quelqu'un d'autre.	Edouard Bourdet]"),
        new fmrCitation("Il faut choisir, dans la vie, entre gagner de l'argent et le dépenser; on n'a pas le temps de faire les deux. [Edouard Bourdet]"),
        new fmrCitation("Il y a des femmes qui n'aiment pas faire souffrir plusieurs hommes a la fois, qui préfèrent s'appliquer a un seul : ce sont les femmes fidèles. [Alfred Capus]"),
        new fmrCitation("Ce qui est grave dans un ménage, c'est quand l'un aime et l'autre pas. Mais s'ils ne s'aiment ni l'un ni l'autre, ils peuvent être très heureux. [Alfred Capus ]"),
        new fmrCitation("A Paris, ce qu'on appelait autrefois l'âge mur tend a disparaître. On reste très jeune très longtemps, puis on devient gâteux. [Alfred Capus]"),
        new fmrCitation("Si j'avais encore l'argent que j'ai dépensé pour boire,qu'est-ce que je pourrais me payer comme apéritifs ! [Celmas]"),
        new fmrCitation("Il y a des femmes qui trouvent à se vendre et qui ne trouveraient pas a se donner ! [Chamfort]"),
        new fmrCitation("La société est divisée en deux classes : ceux qui ont plus de dîners que d'appétit et ceux qui ont plus d'appétit que de dîners. [Chamfort]"),
        new fmrCitation("Apprendre a mourir ! Et pourquoi donc ? On y réussit très bien la première fois! [Chamfort]"),
        new fmrCitation("C'est très curieux : ce sont toujours les célibataires qui vous donnent des conseils pour élever des enfants. [Paul Claudel]"),
        new fmrCitation("De tous les plaisirs, quand il n'en reste plus, il reste toujours celui de se lever de table après un repas ennuyeux. [Paul Claudel]"),
        new fmrCitation("On ne ment jamais autant qu'avant les élections, pendant la guerre et pares la chasse. [Georges Clemenceau]"),
        new fmrCitation("La guerre, c'est une chose trop grave pour la confier a des militaires. [Georges Clemenceau]"),
        new fmrCitation("Un traître est un homme politique qui quitte son parti pour s'inscrire a un autre. Par contre, un converti est un homme politique qui quitte son parti pour s'inscrire au votre. [Georges Clemenceau]"),
        new fmrCitation("La France est un pays extrêmement fertile. On y plante des fonctionnaires, il y pousse des impôts. [Georges Clemenceau]"),
        new fmrCitation("Les fonctionnaires sont un petit peu comme les livres d'une bibliothèque. Ce sont les plus hauts placés qui servent le moins... [Georges Clemenceau]"),
        new fmrCitation("Les miroirs feraient bien de réfléchir avant de renvoyer les images. [Jean Cocteau]"),
        new fmrCitation("Finalement, je crois que j'ai vécu très au-dessus des moyens de mon époque. [Jean Cocteau]"),
        new fmrCitation("Un enfant prodige, c'est un enfant dont les parents ont beaucoup d'imagination. [Jean Cocteau]"),
        new fmrCitation("L'homme est le seul mâle qui batte sa femelle. On doit donc en déduire que l'homme est le plus brutal des mâles... a moins que la femme ne soit, de toutes les femelles, la plus insupportable. [Georges Courteline]"),
        new fmrCitation("L'homme n'est pas fait pour travailler. La preuve, c'est que ca le fatigue. [Georges Courteline]"),
        new fmrCitation("L'administration est un lieu ou les gens qui arrivent en retard croisent dans l'escalier ceux qui partent en avance. [Georges Courteline]"),
        new fmrCitation("La femme ne voit jamais ce que l'on fait pour elle; elle ne voit que ce que l'on ne fait pas. [Georges Courteline]"),
        new fmrCitation("Lorsque ma femme me fait un cadeau, j'ai deux surprises : d'abord le cadeau, ensuite de le payer. [Maurice Donnay]"),
        new fmrCitation("Les chaînes du mariage sont si lourdes qu'il faut être deux pour les porter; quelquefois trois. [Alexandre Dumas]"),
        new fmrCitation("Chez moi, quand on tue le cochon, tout le monde rit ! Sauf le cochon. [Edgar Faure]"),
        new fmrCitation("Le mariage, c'est l'art pour deux personnes de vivre ensemble aussi heureuses qu'elles auraient vécu chacune de leur cote. [Georges Feydau]"),
        new fmrCitation("Quand un philosophe vous répond, on ne comprend même plus ce qu'on lui avait demande. [André Gide]"),
        new fmrCitation("L'égoïste est celui qui n'emploie pas toutes les minutes de sa vie a assurer le bonheur de tous les autres égoïstes. [Lucien Guitry]"),
        new fmrCitation("La réussite, pour un homme, c'est d'être parvenu a gagner plus d'argent que sa femme n'a pu en dépenser. [Sacha Guitry]"),
        new fmrCitation("A l'égard de quelqu'un qui vous prend votre femme, la pire vengeance est de la lui laisser. [Sacha Guitry]"),
        new fmrCitation("Certains hommes n'ont que ce qu'ils méritent; les autres sont célibataires. [Sacha Guitry]"),
        new fmrCitation("Tous les hommes naissent comédiens, sauf quelques acteurs. [Sacha Guitry]"),
        new fmrCitation("Quand on me parle d'une femme cultivée, je l'imagine avec des carottes dans les oreilles et du cerfeuil entre les doigts de pied. [Sacha Guitry]"),
        new fmrCitation("Quand un barbier lui demande comment il veut qu'on lui coupe les cheveux, le sage répond: en silence. [Confucius]"),
        new fmrCitation("La seule chose plus difficile à digérer qu'une salade d'avocat, c'est une facture d'avocat. [Confucius]"),
        new fmrCitation("Quand un patron vous dit que sa compagnie est comme une grande famille, attendez-vous à travailler pour ses enfants et ses neveux. [Confucius]"),
        new fmrCitation("Si votre psychanalyste s'endort devant vous, il y a un truc infaillible pour le réveiller: ouvrez doucement votre portefeuille. [Woody Allen]"),
        new fmrCitation("Les juges ne voyagent jamais, parce qu'on ne peut être à la fois juge et parti. [Confucius]"),
        new fmrCitation("L'éternité c'est long, surtout vers la fin... [Woody Allen]"),
        new fmrCitation("Il ne faut jamais regarder quelqu'un qui dort. C'est comme si on ouvrait une lettre qui ne vous est pas adressée. [Sacha Guitry]"),
        new fmrCitation("Il n'y a pas de bonheur parfait ! dit l'homme quand sa belle-mère mourut et qu'on lui présenta la note des pompes funèbres. [Jerome K. Jerome]"),
        new fmrCitation("De temps en temps, une femme est un substitut convenable a la masturbation. Mais bien sur, il faut beaucoup d'imagination. [Karl Kraus]"),
        new fmrCitation("Les gens couverts de croix me font irrésistiblement penser à un cimetière. [Paul Leautaud]"),
        new fmrCitation("La vie ne vaut rien. Mais rien ne vaut la vie. [André Malraux]"),
        new fmrCitation("Si l'on y réfléchit bien, le Christ est le seul anarchiste qui ait vraiment réussi. [André Malraux]"),
        new fmrCitation("Je désire être incinéré et je veux que 10 % de mes cendres soient versées a mon impresario. [Groucho Marx]"),
        new fmrCitation("Les hommes sont comme... l'horoscope. Ils vous disent toujours quoi faire et habituellement ils se trompent.. [Confucius]"),
        new fmrCitation("La nature est prévoyante : elle a fait pousser la pomme en Normandie sachant que c'est dans cette région qu'on boit le plus de cidre. [Henri Monnier]"),
        new fmrCitation("Un soldat doit être prêt a mourir pour sa patrie, même au péril de sa vie. [Henri Monnier]"),
        new fmrCitation("Si haut que l'on soit place, on n'est jamais assis que sur son cul. [Montaigne]"),
        new fmrCitation("On parle toujours du boulevard des Filles du Calvaire, mais jamais du calvaire des filles du boulevard. [Rochefort]"),
        new fmrCitation("Les cures se consolent de n'être pas maries quand ils entendent les femmes se confesser. [Armand Salacroix]"),
        new fmrCitation("Que l'on meurt gros ou maigre, la différence, c'est pour les porteurs. [Peter Ustinov]"),
        new fmrCitation("Dieu créa l'homme et, ne le trouvant pas assez seul, il lui donna une compagne pour lui faire mieux sentir sa solitude. [Paul Valery]"),
        new fmrCitation("Il ne faut jamais juger les gens sur leurs fréquentations : Judas, par exemple, avait des amis irréprochables. [Verlaine]"),
        new fmrCitation("Si Dieu nous a faits a son image, nous lui avons bien rendu. [Voltaire]"),
        new fmrCitation("J'ai souvent remarqué, pour ma part, que les cocus épousent de préférence les femmes adultères. [Alphonse Allais]"),
        new fmrCitation("Dieu a sagement agi en plaçant la naissance avant la mort ; sans cela, que saurait-on de la vie ? [Alphonse Allais]"),
        new fmrCitation("Un concerné n'est pas obligatoirement un imbécile encerclé. [Pierre Dac]"),
        new fmrCitation("Le meilleur moyen de faire tourner la tête à une femme, c'est de lui dire qu'elle a un joli profil. [Sacha Guitry]"),
        new fmrCitation("Il y a des femmes dont l'infidélité est le seul lien qui les attache encore à leur mari. [Sacha Guitry]"),
        new fmrCitation("Expérience: nom dont les hommes baptisent leurs erreurs. [Oscar Wilde]"),
        new fmrCitation("J'aime les hommes qui ont de l'avenir et les femmes qui ont un passé. [Oscar Wilde]"),
        new fmrCitation("La dictature, c'est 'ferme ta gueule', et la démocratie, c'est 'cause toujours'. [Woody Allen]"),
        new fmrCitation("Les proverbes ressemblent aux papillons; on en attrape quelques-uns, les autres s'envolent [W.Wander]"),
        new fmrCitation("Rien n'est plus dangereux qu'une idée, quand on n'a qu'une idée. [Alain]"),
        new fmrCitation("Si Dieu avait voulu que l'on prit la Vie sérieusement, il ne nous aurait pas donné le sens de l'humour. [Anonyme]"),
        new fmrCitation("Un concerné n'est pas obligatoirement un imbécile encerclé. [Pierre Dac]"),
        new fmrCitation("Il y a des femmes dont l'infidélité est le seul lien qui les attache encore à leur mari. [Sacha Guitry]"),
        new fmrCitation("Les champignons poussent dans les endroits humides. C'est pourquoi ils ont la forme d'un parapluie. [Alphonse Allais]"),
        new fmrCitation("Il y a deux ans que je n'ai pas parle a ma femme, c'était pour ne pas l'interrompre. [Jules Renard]"),
        new fmrCitation("C'est parce que la fortune vient en dormant que celle-ci arrive si lentement. [Alphonse Allais]"),
        new fmrCitation("C'est quand on serre une femme de trop près qu'elle trouve qu'on va trop loin. [Alphonse Allais]"),
        new fmrCitation("Il n'y a pas de fonctionnaires travailleurs, il n'y a que des fonctionnaires insomniaques. [Confucius]"),
        new fmrCitation("Et Jean tua Madeleine. Ce fut à peu près vers cette époque que Madeleine perdit l'habitude de tromper Jean. [Alphonse Allais]"),
        new fmrCitation("Il vaut mieux passer à La Poste hériter qu'à la postérité! [Alphonse Allais]"),
        new fmrCitation("Je ne prendrai pas de calendrier cette année, car j'ai été très mécontent de celui de l'année dernière! [Alphonse Allais]"),
        new fmrCitation("L'avantage des médecins, c'est que lorsqu'ils commettent une erreur, ils l'enterrent tout de suite... [Alphonse Allais]"),
        new fmrCitation("Les jambes permettent aux hommes de marcher et aux femmes de faire leur chemin. [Alphonse Allais]"),
        new fmrCitation("La politique est l'art d'obtenir de l'argent des riches et des suffrages des pauvres, sous prétexte de les protéger les uns des autres. [Anonyme]"),
        new fmrCitation("Le dernier refuge contre les téléphones portables : les cabines téléphoniques. [Anonyme]"),
        new fmrCitation("Qui pisse loin ménage ses pompes. [Anonyme]"),
        new fmrCitation("Toute chose a une fin, sauf le saucisson qui en a deux [Anonyme]"),
        new fmrCitation("Une robe de femme, doit être comme une plaidoirie : assez longue pour couvrir le sujet, assez courte pour être suivie. [Anonyme]"),
        new fmrCitation("La célébrité m'a apporté un gros avantage : les femmes qui me disent non sont plus belles qu'autrefois. [Woody Allen]"),
        new fmrCitation("Si je fais si bien l'amour, c'est que je me suis longtemps entraîné tout seul. [Woody Allen]"),
        new fmrCitation("Un conducteur dangereux, c'est celui qui vous dépasse malgré tous vos efforts pour l'en empêcher. [Woody Allen]"),
        new fmrCitation("L'argent est plus utile que la pauvreté, ne serait-ce que pour des questions financières. [Woody Allen]"),
        new fmrCitation("Elles croient que tous les hommes sont pareils, parce qu'elles se conduisent de la même manière avec tous les hommes. [Sacha Guitry]"),
        new fmrCitation("Il y a celles qui disent qu'elles ne sont pas à vendre, et qui n'accepteraient pas un centime de vous! Ce sont généralement celles-là qui vous ruinent. [Sacha Guitry]"),
        new fmrCitation("Je suis en faveur de la coutume qui veut qu'un homme baise la main d'une femme la première fois qu'il la voit. Il faut bien commencer par un endroit quelconque. [Sacha Guitry]"),
        new fmrCitation("Le bonheur à deux, ça dure le temps de compter jusqu'à trois! [Sacha Guitry]"),
        new fmrCitation("Quand on ment à une femme, on a l'impression qu'on se rembourse. [Sacha Guitry]"),
        new fmrCitation("Si le plus grand plaisir des hommes est de se payer les corps des femmes, le plus grand plaisir des femmes est de se payer la tête des hommes. [Sacha Guitry]"),
        new fmrCitation("La moitié des hommes politiques sont des bons à rien. Les autres sont prêts à tout. [Coluche]"),
        new fmrCitation("Il ne faut jamais faire de projets, surtout en ce qui concerne l'avenir. [Alphonse Allais]"),
        new fmrCitation("L'avenir appartient à ceux qui se lèvent tôt, c'est une connerie. Prenez les éboueurs... [Jean Yanne]"),
        new fmrCitation("Un imprimeur est un homme qui ne manque pas de caractère et qui cherche à faire bonne impression. [Serge Mirjean]"),
        new fmrCitation("Il y en a qui sont faits pour commander et d'autres pour obéir. Moi je suis fait pour les deux : ce midi, j'ai obéi à mes instincts en commandant un deuxième pastis. [Pierre Dac]"),
        new fmrCitation("Défaite : déconfiture et pas de pot. [Anonyme]"),
        new fmrCitation("Les catholiques existent pour acheter au détail ce que les juifs n'achètent qu'en gros. [Coluche]"),
        new fmrCitation("Si c'est les meilleurs qui partent les premiers, que penser alors des éjaculateurs précoces ? [Pierre Desproges]"),
        new fmrCitation("Les hommes sont comme... une tempête de neige. Vous ne savez jamais quand ils vont venir,à combien de centimètres vous aurez affaire et combien de temps ca va durer. [O [jt]"),
        new fmrCitation("Quelle est la différence entre un meurtrier et un homme qui vient de fairel'amour ? - Aucune. Ils ne savent pas comment se débarrasser du corps. [DESPROGES [jt]"),
        new fmrCitation("Je n'ai pas assisté à beaucoup de courses de spermatozoïdes mais j'ai donné beaucoup de départs. [Olivier de Kersauson]"),
        new fmrCitation("Il ne faut pas désespérer des imbéciles. Avec un peu d'entraînement, on peut arriver à en faire des militaires. [Pierre Desproges]"),
        new fmrCitation("Dieu a dit : 'Il faut partager'. Les riches auront la nourriture, les pauvres de l'appétit. [Coluche]"),
        new fmrCitation("Il est faux que les femmes frigides vivent plus longtemps que les autres. Simplement, le temps leur semble plus long. [François Cavanna]"),
        new fmrCitation("Je me suis marié deux fois, deux échecs : la première s'est barrée, la seconde est restée [Un mec]"),
        new fmrCitation("Un enfant demande à son père : 'Papa, qui m'a donné mon intelligence ?' Le père dit : 'Ça doit être ta mère parce que moi je l'ai encore.' [Un père]"),
        new fmrCitation("Pourquoi Dieu a-t-il créé l'homme avant la femme ?  Pour lui donner juste le temps de savoir ce que pouvait être le paradis... [Le Coran]"),
        new fmrCitation("L'amour c'est un sport. Surtout s'il y en a un des deux qui ne veut pas. [Jean Yanne]"),
        new fmrCitation("Pour le pape, le plus dur c'est de ne pas avoir d'homologue avec qui causer boulot [Jean Yanne]"),
        new fmrCitation("La dernière fois que j'ai pénétré une femme, c'était en visitant la statue de la Liberté. [Woody Allen]"),
        new fmrCitation("Au commencement, Dieu ne savait pas qu'il était Dieu, puisqu'il était tout seul. Pour savoir qu'on est Dieu, il faut être deux: un qui est Dieu, et l'autre qui lui dit: «Mon Dieu». [François Cavanna]"),
        new fmrCitation("L'hirondelle ne fait pas le printemps, mais le chameau fait le désert. [François Cavanna]"),
        new fmrCitation("Comme tous les verseau, je ne crois pas à l'horoscope. [Anonyme]"),
        new fmrCitation("Votre enfant devient adolescent lorsqu'il cesse de demander d'où il vient et qu'il ne dit plus où il va. [Anonyme]"),
        new fmrCitation("Se marier, c'est partager à deux les problèmes que l'on n'aurait pas eu tout seul. [Anonyme]"),
        new fmrCitation("Pour défendre une cause, un avocat met sa robe. Une femme... l'enlève. [Anonyme]"),
        new fmrCitation("Ce n'est pas en tournant le dos aux choses qu'on leur fait face. [Pierre Dac]"),
        new fmrCitation("On croit souvent qu'un appartement est bas de plafond, alors qu'il est tout simplement haut de plancher. [Pierre Dac]"),
        new fmrCitation("On dit d'un accusé qu'il est cuit quand son avocat n'est pas cru [Pierre Dac]"),
        new fmrCitation("Sans l'invention de la roue, les coureurs du Tour de France seraient condamnés à porter leur bicyclette sur le dos. [Pierre Dac]"),
        new fmrCitation("Après l'amour, dix pour cent des hommes se retournent sur leur côté droit et s'endorment, dix pour cent font de même sur le côté gauche. Les autres se rhabillent et rentrent chez eux. [Francis Blanche]"),
        new fmrCitation("A la sécurité sociale, tout est assuré. Sauf la pendule. Ca, on ne risque pas de la voler, le personnel a les yeux constamment fixés dessus. [Coluche]"),
        new fmrCitation("Dans les restaurants chinois, la nuit tous les chats sont cuits [Confucius]"),
        new fmrCitation("Quand vous voulez vous faire dire que vos plats fondent dans la bouche, servez des plats congelés. [Confucius]"),
        new fmrCitation("L'appétit vient en faisant la queue. [Confucius]"),
        new fmrCitation("L'appétit vient en mangeant, la soif s'en va en buvant [Rabelais]"),
        new fmrCitation("En matière de sexe, la plupart des hommes se prennent pour des dieux. [Manque de pot, en matière de sexe, la plupart des femmes sont athées. [Bernard Lherbier]"),
        new fmrCitation("Les femmes préfèrent être belles, plutôt qu'intelligentes parce que Chez les hommes, il y a plus d'idiots que d'aveugles. [Yvonne Printemps]"),
        new fmrCitation("Il faut user de tout avec modération, surtout de la modération. [Richard Bates]"),
        new fmrCitation("Quand la vérité sort de la bouche d'un politicien, c'est parce qu'il a été mal cité par un journalisme. [Confucius]"),
        new fmrCitation("Je suis parti à Lourdes avec ma femme . Il n'y pas eu de miracle , je suis revenu avec. [Seymour Brussel]"),
        new fmrCitation("Je dois avouer que ,lors de mon divorce, les torts était partagés :50% des torts à ma femme et 50% à sa mère [François Olléry]"),
        new fmrCitation("Un politicien honnête, c'est celui qui reste fidèle à celui qui l'a acheté. [Confucius]"),
        new fmrCitation("C'est vraiment dommage que 90% des politiciens donnent une mauvaise réputation aux 10% qui restent. [Henry Kissinger]"),
        new fmrCitation("Chez un homme politique, les études c'est quatre ans de droit, puis toute une vie de travers. [Coluche]"),
        new fmrCitation("Nul n'est prophète en son pays, surtout pas les météorologues. [Confucius]"),
        new fmrCitation("Le sage ne dit pas ce qu'il sait et le sot ne sait pas ce qu'il dit [Confucius]"),
        new fmrCitation("Vous avez beau tuer le temps, c'est lui qui finira par vous enterrer... [Confucius]"),
        new fmrCitation("Quand on pointe la lune du doigt, l'imbécile regarde le doigt [Confucius]"),
        new fmrCitation("Si on bâtissait la maison du bonheur, la plus grande pièce en serait la salle d'attente. [Confucius]"),
        new fmrCitation("L'humour, c'est de savoir que tout, absolument tout, est drôle. Du moment que c'est aux autres que  ça arrive. [Confucius]"),
        new fmrCitation("- Que faisiez vous avant de vous marier ? - Avant, je faisais ce que je voulais. [Marcel Jouhandeau]"),
        new fmrCitation("J'ai un copain qui a fait un mariage d'amour.Il a épousé une femme riche... Il aimait l'argent [Coluche]"),
        new fmrCitation("Un imbécile qui marche va plus loin qu'un intellectuel assis. [Michel Audiard]"),
        new fmrCitation("On s'aperçoit qu'on vieillit quand on voit son médecin plus souvent que ses enfants. [Confucius]"),
        new fmrCitation("Quand il veut se sentir jeune de coeur, le sage se fait poser un pacemaker. [Confucius]"),
        new fmrCitation("Le lit est l'endroit le plus dangereux du monde : 80% des gens y meurent. [Mark Twain]"),
        new fmrCitation("Ce sont toujours les employés qui font des erreurs. Les patrons, eux font des expériences. [Confucius]"),
        new fmrCitation("En 2002, dans le monde entier, on a dépensé 5 fois plus d'argent pour des implants mammaires et du Viagra que pour la recherche contre la maladie d'Alzheimer.On peut donc conclure que dans 30 ans, il y aura un très grand nombre de personnes avec de gros nichons et de superbes érections, mais incapables de se rappeler à quoi ça sert [Anonyme]"),
        new fmrCitation("- Moi aussi je me suis marié, mais j'avais une excuse : le lave-vaisselle n'existait pas encore [Patrick Font]"),
        new fmrCitation("- Moi, je n'avais pas couché avec ma femme avant de l'épouser, et toi ? - Je ne sais pas elle s'appelle comment , ta femme ? [Fernand Raynaud]"),
        new fmrCitation("Ma femme et moi avons été heureux 25 ans. C'est à cet âge-là que nous nous sommes rencontrés ... [Sacha Guitry]"),
        new fmrCitation("Contrairement à ce que croient les pauvres, l'argent ne fait pas le bonheur des riches. Mais contrairement à ce que croient les riches, il ferait le bonheur des pauvres. [Jean d'Ormesson [jt]"),
        new fmrCitation("Etre bête, égoiste et et avoir un bonne santé: voilà les 3 conditions du bonheur. [G.Flaubert]"),
        new fmrCitation("Le bonheur humain est composé de tant de pièces qu'il en manque toujours. [Bossuet]"),
        new fmrCitation("On ne peut se rendre maitre des choses en les possédant toutes; il faut s'en rendre maître en les méprisants toutes. [Bossuet]"),
        new fmrCitation("Le coté positif de la mort est qu'on peut l'être en restant couché. [Woody Allen]"),
        new fmrCitation("Etre heureux c'est avoir surmonté l'inquiétude du bonheur. [M. Maeterlink]"),
        new fmrCitation("Celui qui sait rire de lui-même n'a pas fini de rigoler [Confucius]"),
        new fmrCitation("Dieu créa les mathématiques, puis la femme et dit :'la femme sera l'addition des plaisirs, la multiplication des ennuis, la division des copains' [La Bible]"),
        new fmrCitation("En fait l'important ne serait pas de réussir sa vie, mais de rater sa mort. [Jean Yanne]"),
        new fmrCitation("Un optimiste est celui qui achète à un Juif et veut vendre à un Ecossais [Henry Louis Mencken]"),
        new fmrCitation("Il faut faire des enfants quand on est vieux, parce qu'on les emmerde pas longtemps. [Jean Yanne]"),
        new fmrCitation("Les femmes qui veulent être les égales des hommes manquent sérieusement d'ambition. [Jean-Marc Reiser]"),
        new fmrCitation("En tous pays, avant de juger un homme, le monde écoute ce qu'en pense sa femme. [Honore de Balzac]"),
        new fmrCitation("La femme serait vraiment l'égale de l'homme le jour ou, a un poste important, on désignerait une femme incompétente [Françoise Giroud]"),
        new fmrCitation("Les hommes sont comme... le café. Les meilleurs sont riches, chauds et peuvent te tenir éveillée toute la nuit. [Martine]"),
        new fmrCitation("Le meilleur moyen de prendre un train a l'heure, c'est de s'arranger pour rater le précédant. [Marcel Achard]"),
        new fmrCitation("L'oubli de ses propres fautes est la plus sure des absolutions. [Konrad Adenauer]"),
        new fmrCitation("Il est toujours avantageux de porter un titre nobiliaire. Etre 'de quelque chose', ça pose un homme, comme être 'de Garenne', ça pose un lapin. [Alphonse Allais]"),
        new fmrCitation("L'argent aide a supporter la pauvreté. [Alphonse Allais]"),
        new fmrCitation("Les pommes de terre cuites sont tellement plus faciles a digérer que les pommes en terre cuite ! [Alphonse Allais]"),
        new fmrCitation("Une auto-stoppeuse est une jeune femme généralement jolie et court vêtue qui se trouve sur votre route quand vous êtes avec votre femme. [Woody Allen]"),
        new fmrCitation("Pourquoi contredire une femme ? Il est tellement plus simple d'attendre qu'elle change d'avis ! [Jean Anouilh]"),
        new fmrCitation("Si Dieu avait voulu que l'on prit la Vie sérieusement, il ne nous aurait pas donne le sens de l'humour. [Anonyme.]"),
        new fmrCitation("Si Dieu descendait sur la Terre, tous les peuples se mettraient a genoux, excepte les Français qui diraient : ' Ah ! Vous êtes là ! C'est pas trop tôt ! On va pouvoir discuter un peu ! ' [Lord Balfour]"),
        new fmrCitation("Avant de choisir le prénom d'un garçon, pensez toujours a la femme qui aura a le murmurer plus tard. [Barbey d'Aurevilly]"),
        new fmrCitation("Les hommes sont toujours sincères. Ils changent de sincérité, voilà tout. [Tristan Bernard ]"),
        new fmrCitation("Avec les femmes, il faudrait que les paroles soient d'autant plus respectueuses que les gestes le deviennent de moins en moins. [Tristan Bernard ]"),
        new fmrCitation("On a le droit de dire du mal des femmes; on n'a pas le droit de dire du mal d'une femme. [Alexandre Dumas ]"),
        new fmrCitation("On ne prête qu'aux riches, et on a bien raison, parce que les autres remboursent difficilement. [Tristan Bernard]"),
        new fmrCitation("Il ne faut compter que sur soi-même. Et encore, pas beaucoup. [Tristan Bernard]"),
        new fmrCitation("L'amour rend aveugle, le mariage rend la vue. [Anne Roumanov]"),
        new fmrCitation("il faut décider d'être heureux parce que c'est bon pour la santé [Voltaire]"),
        new fmrCitation("On compare souvent le mariage à une loterie. C'est une erreur car, à la loterie on peut parfois gagner [Bernard Shaw]"),
        new fmrCitation("Ne dites pas de mal de la masturbation. Après tout, c'est une façon de faire l'amour avec quelqu'un qu'on aime [Woody Allen]"),
        new fmrCitation("Il vaut mieux qu'il pleuve un jour comme aujourd'hui, plutot qu'un jour ou il fait beau. [Pierre Dac]"),
        new fmrCitation("L'erreur est humaine mais un veritable desastre necessite un ordinateur. [Bill Gates]"),
        new fmrCitation("Le jour le plus long ne fera jamais plus de 24 heures. [Une blonde.]"),
        new fmrCitation("Si l'on veut gagner sa vie, il suffit de travailler. Si l'on veut devenir riche, il faut trouver autre chose. [Alphonse CARR]"),
        new fmrCitation("Le travail c'est la santé ; ne rien faire, c'est la conserver. [Henri Salvador]"),
        new fmrCitation("Le travail fatigue même les ânes. [Matheo Aleman]"),
        new fmrCitation("Au travail, le plus difficile, c'est d'allumer la petite lampe du cerveau. Après, ça brûle tout seul. [Jules Renard]"),
        new fmrCitation("Eureka ! [Archimède]"),
        new fmrCitation("Comment on s'aperçoit qu'on est vieux ? quand même bronzé, on reste moche. [Jean Louis Fournier]"),
        new fmrCitation("le sage ne dit pas ce qu'il pense, mais il pense ce qu'il dit [Lessing]"),
        new fmrCitation("Abusus non tollit usum : L'abus n'exclut pas l'usage"),
        new fmrCitation("Acta est fabula : La pièce est jouée"),
        new fmrCitation("Age quod agis : Fais ce que tu fais"),
        new fmrCitation("Alea jacta est : Le sort en est jeté"),
        new fmrCitation("Ars longa, vita brevis : L'art est long, la vie est courte"),
        new fmrCitation("Audaces fortuna juvat : La fortune favorise les audacieux"),
        new fmrCitation("Aut Caesar, aut nihil : Ou empereur, ou rien"),
        new fmrCitation("Ave Caesar, morituti te salutant : Salut César, ceux qui vont mourir te saluent"),
        new fmrCitation("Beati pauperes spiritu : Bienheureux les pauvres en esprit"),
        new fmrCitation("Beati possidentes : Heureux ceux qui possèdent"),
        new fmrCitation("Contraria contrarii curantur : Les contraintes se guérissent par les contraintes"),
        new fmrCitation("Credo quia absurdum : Je le crois parce que c'est absurde"),
        new fmrCitation("De gustibus et coloribus non disputandum : Des goûts et des couleurs, il ne faut pas discuter"),
        new fmrCitation("De minimis non curat praetor : Le prêteur ne s'occupe pas des petites affaires"),
        new fmrCitation("Divide ut regnes : Divise, afin de régner"),
        new fmrCitation("Doctus cum libro : Savant avec le livre"),
        new fmrCitation("Donec eris felix, multos numerabis amicos : Tant que tu seras heureux, tu compteras beaucoups d'amis"),
        new fmrCitation("Dura lex, sed lex : La loi est dure, mais c'est la loi"),
        new fmrCitation("Eppur, si muove ! : Et pourtant, elle tourne !"),
        new fmrCitation("Errare humanum est, perseverare diabolicum : L'erreur est humaine, perseverer est diabolique"),
        new fmrCitation("Ex nihilo nihil : Rien [ne vient] de rien"),
        new fmrCitation("Felix qui potuit rerum cognoscere causas : Heureux celui qui a pu pénétrer les causes secrètes des choses"),
        new fmrCitation("Festina lente : Hâte-toi lentement"),
        new fmrCitation("Fugit irreparabile tempus : Le temps fuit irréparable"),
        new fmrCitation("Homo homini lupus : L'homme est un loup pour l'homme"),
        new fmrCitation("Ignoti nulla cupido : On ne désire pas ce qu'on ne connaît pas"),
        new fmrCitation("Intelligenti pauca : A qui sait comprendre, peut de mots suffisent"),
        new fmrCitation("Ira furor brevis est : La colère est une courte folie"),
        new fmrCitation("Mememto, homo, quia pulvis es et in pulverem reverteris : Souviens-toi, homme, que tu es poussière et que tu retourneras en poussière"),
        new fmrCitation("Mens sana in corpore sano : Ame saine dans un corps sain"),
        new fmrCitation("Mors ultima ratio : La mort est la raison finale de tout"),
        new fmrCitation("Naturam expelles furca, tamen usque recurret : Chassez la nature avec une fourche, elle reviendra toujours en courant"),
        new fmrCitation("Non omnia possumus omnes : Nous ne pouvons tous faire toutes choses"),
        new fmrCitation("Oderint, dum metuant : Qu'ils me haissent, pourvu qu'ils me craignent"),
        new fmrCitation("Omnis homo mendax : Tout homme est menteur"),
        new fmrCitation("Qui bene amat, bene castigat : Qui aime bien, châtie bien"),
        new fmrCitation("Qui habet aures audiendi, audiat : Que celui qui a des oreilles pour entendre entende"),
        new fmrCitation("Qui nescit dissimulare, nescit regnare : Celui qui ne sait pas dissimuler ne sait pas régner"),
        new fmrCitation("Quot capita, tot sensus : Autant de têtes, autant d'avis"),
        new fmrCitation("Quotidie morior : je meurs chaque jour"),
        new fmrCitation("Sapiens nihil affirmat quod non probet : Le sage n'affirme rien qu'il ne prouve"),
        new fmrCitation("Sint ut sunt, aut non sint : Qu'ils soient ce qu'ils sont, ou qu'ils ne soient pas"),
        new fmrCitation("Si vis pacem, para bellum : Si tu veux la paix, prépare la guerre"),
        new fmrCitation("Sol lucet omnibus : Le soleil luit pour tout le monde"),
        new fmrCitation("Spiritus promptus est, caro autem infirma : L'esprit est prompt, mais la chair est faible"),
        new fmrCitation("Sublata causa, tollitur effectus : La cause supprimée, l'effet disparaît"),
        new fmrCitation("Tarde venientibus ossa : Ceux qui viennent tard à table ne trouvent plus que des os"),
        new fmrCitation("Tempus edax rerum : Le temps qui détruit tout"),
        new fmrCitation("Testis unus, testis nullus : Témoin seul, témoin nul"),
        new fmrCitation("Tu quoque, fili ! : Toi aussi, mon fils !"),
        new fmrCitation("Vae soli ! : Malheur à l'homme seul !"),
        new fmrCitation("Vanitas vanitatum, et omnia vanitas : Vanité des vanités, et tout est vanité"),
        new fmrCitation("Veni, vidi, vici : Je suis venu, j'ai vu, j'ai vaincu"),
        new fmrCitation("Verba volant, scripta manent : Les paroles s'envolent, les écrits restent"),
        new fmrCitation("Veritas odium parit : La franchise engendre la haine"),
        new fmrCitation("Volenti non fit injuria : On ne fait pas de tort à celui qui consent"),
        new fmrCitation("Vulnerant omnes, ultima necat : Toutes blessent, la dernière tue"),
        new fmrCitation("Plus un homme devient sage, moins il cherche à prendre la parole. [Hazrat Ali]"),
        new fmrCitation("Tant qu'un homme n'a pas découvert quelque chose pour lequel il serait prêt à mourir, il n'est pas à même de vivre. [Martin Luther King]"),
        new fmrCitation("Qui sait si vivre est ce qu'on appelle mourir et si mourir c'est vivre ? [Euripide]"),
        new fmrCitation("Mourir fait partie de la vie. Et ceux qui ont peur de la mort sont aussi ceux qui ont peur de vivre.  [Clark Gable - Dialogue du film Misfits]"),
        new fmrCitation("Veux-tu apprendre à bien vivre, apprends auparavant à bien mourir. [Confucius]"),
        new fmrCitation("Qui apprendrait les hommes à mourir, leur apprendrait à vivre. [Montaigne]"),
        new fmrCitation("Ce n'est rien de mourir ; c'est affreux de ne pas vivre. [Victor Hugo]"),
        new fmrCitation("Ce qu'on appelle raison de vivre est en même temps une excellente raison de mourir. [Albert Camus]"),
        new fmrCitation("L'esprit philosophique consiste à préférer aux mensonges qui font vivre les vérités qui font mourir. [Gustave Thibon]"),
        new fmrCitation("Le mensonge c'est la foi des maîtres et des esclaves ! La vérité, c'est le dieu des hommes libres ! [Maxime Gorki]"),
        new fmrCitation("Je suis un âne, tu es un âne. Où est le problème ? [A.de Mello]"),
        new fmrCitation("On est en droit de se demander s'il y a une vie avant la mort. [Coluche]"),
        new fmrCitation("De même que je refuse d'être un esclave, je refuse d'être un maître. Telle est mon idée de la démocratie. [Abraham Lincoln]"),
        new fmrCitation("L'homme moderne est l'esclave de la modernité : il n'est point de progrès qui ne tourne pas à sa plus complète servitude. [Paul Valéry]"),
        new fmrCitation("En donnant la liberté aux esclaves, nous assurons celle des hommes libres. [Abraham Lincoln]"),
        new fmrCitation("Nul n'est plus esclave que celui qui se croit libre sans l'être. [Goethe]"),
        new fmrCitation("Lorsque l'homme s'habitue à voir les autres porter les chaînes de l'esclavage, c'est qu'il accepte lui-même un jour de les porter. [Abraham Lincoln]"),
        new fmrCitation("Où il n'y a point de maître, tout le monde est maître ; où tout le monde est maître, tout le monde est esclave. [Bossuet]"),
        new fmrCitation("L'esclave est un serviteur qui ne discute point et se soumet à tout sans murmure. Quelquefois il assassine son maître mais il ne lui résiste jamais. [Alexis de Tocqueville]"),
        new fmrCitation("Si un homme ne fait que ce qu'on exige de lui, il est un esclave. S'il en fait plus, il est un homme libre. [Proverbe chinois]"),
        new fmrCitation("L'écureuil a beau être petit, il n'est pas l'esclave de l'éléphant. [Proverbe]"),
        new fmrCitation("Donner un verre d'eau en échange d'un verre d'eau n'est rien ; la vraie grandeur consiste à rendre le bien pour le mal. [Gandhi]"),
        new fmrCitation("Tous les hommes seraient des tyrans s'ils le pouvaient. [Daniel Defoe]"),
        new fmrCitation("L'amour et la tolérance sont la seule réponse au problème de la vie. Ce précepte, très simple, et infiniment difficile à appliquer, peut être accepté, compris par quiconque, croyant ou non-croyant. C'est la seule voie. [Anthony Burgess]"),
        new fmrCitation("La règle d'or de la conduite est la tolérance mutuelle, car nous ne penserons jamais tous de la même façon, nous ne verrons qu'une partie de la vérité et sous des angles différents. [Gandhi]"),
        new fmrCitation("La tolérance ne devrait être qu'un état transitoire. Elle doit mener au respect. Tolérer c'est offenser. [Goethe]"),
        new fmrCitation("Je n'aime pas le mot tolérance, mais je n'en trouve pas de meilleur. [Gandhi]"),
        new fmrCitation("La tolérance est un exercice et une conquête sur soi. [Albert Memmi]"),
        new fmrCitation("La non-violence est la loi de notre espèce tout comme la violence est la loi de l'animal. [Gandhi]"),
        new fmrCitation("La seule façon d'accomplir est d'être. [Lao Tseu]"),
        new fmrCitation("Une religion meurt quand il est prouvé qu'elle était vraie. La science est le recueil des religions défuntes. [Anonyme]"),
        new fmrCitation("L'homme n'a inventé Dieu qu'afin de pouvoir vivre sans se tuer. [Dostoïevski]"),
        new fmrCitation("Ce qui est étonnant, ce n'est pas que Dieu existe en réalité mais que cette idée de la nécessité de Dieu soit venue à l'esprit d'un animal féroce et méchant comme l'homme, tant elle est sainte, touchante, sage, tant elle fait honneur à l'homme. [Dostoïevski]"),
        new fmrCitation("La peur est la malédiction de l'homme. [Dostoïevski]"),
        new fmrCitation("Supposons que Dieu n'existe pas. D'où vient alors tout le mal dont l'homme est capable ? Vous êtes bien obligé de reconnaître qu'il vient de l'homme et de nulle part ailleurs. Ce qui m'émerveille chez les athées, ou du moins chez certains d'entre eux, c'est que, ayant perdu la confiance en Dieu, ils puissent continuer de la garder en l'homme. [Shafique Keshanjee]"),
        new fmrCitation("Dieu n'est pas venu supprimer la souffrance. Il n'est même pas venu l'expliquer. Mais il est venu la remplir de sa présence. [Paul Claudel]"),
        new fmrCitation("Croire ou ne pas croire en Dieu relève de la même attitude, l'ignorance."),
        new fmrCitation("Dieu est l'alibi du Diable. [Nietzsche]"),
        new fmrCitation("Mourir pour des idées, d'accord, mais de mort lente...  [Georges Brassens]"),
        new fmrCitation("Le mot que tu n'as pas dit est ton esclave. Le mot que tu as dit est ton maître. [Proverbe oriental]"),
        new fmrCitation("Un père n'est pas là pour fournir des réponses, mais pour montrer l'exemple. Les fils, il ne faut surtout pas les rassurer : il s'agit de les inspirer. [Eric Neuhoff]"),
        new fmrCitation("N'oublions pas que les enfants suivent les exemples mieux qu'ils n'écoutent les conseils. [Roy L. Smith]"),
        new fmrCitation("On est en droit de se demander s'il y a une vie avant la mort ? [Coluche]"),
        new fmrCitation("Rien n'a plus de force qu'une idée dont l'heure est venue. [Victor Hugo]"),
        new fmrCitation("La meilleure façon de réaliser ses rêves est de se réveiller. [Paul Valéry]"),
        new fmrCitation("Le seul moyen de changer est de changer votre compréhension des choses. Mais qu'est-ce que cela veut dire ? [Anthony de Mello]"),
        new fmrCitation("Seul celui qui change peut rester fidèle à lui-même. [Wolf Biermann]"),
        new fmrCitation("Se poser les bonnes questions, c'est se donner une chance de trouver les bonnes réponses."),
        new fmrCitation("Le vrai changement est celui qui n'est pas voulu."),
        new fmrCitation("T'accepter, c'est la première sincérité ; aimer, c'est la première loi ; apprendre à être simple, c'est la première science. [JM Poirier]"),
        new fmrCitation("Ne sais-tu pas que dans chacune de tes actions, l'histoire entière du devenir se répète en abrégé ? [Friedrich Nietzsche]"),
        new fmrCitation("Le plus grand plaisir que je connaisse est de faire une bonne action en secret et qu'elle soit découverte par hasard. [Charles Lamb]"),
        new fmrCitation("Les bonnes actions accomplies dans la jeunesse sont les vivres de la vieillesse. [Léon VI Le Sage]"),
        new fmrCitation("Beaucoup de bonheur se perd...à le rechercher. [Un sage]"),
        new fmrCitation("Il accusait toujours les miroirs d'être faux. [Jean de la Fontaine]"),
        new fmrCitation("Un jour, quand nous aurons maîtrisé les vents, les vagues, les marées et la pesanteur, nous exploiterons l'énergie de l'amour. Alors, pour la seconde fois dans l'histoire du monde, l'homme aura découvert le feu. [Pierre Teilhard de Chardin]"),
        new fmrCitation("Et là où l'amour n'existe pas, la raison, elle aussi, est absente. [Fiodor Dostoïevski]"),
        new fmrCitation("J'aime vraiment la vie. Il faut vivre comme si c'était le premier jour, comme si l'on sortait de la mort et qu'on voulait tout embrasser. Il faut se jeter dans les choses sans savoir. [Le ténor mexicain Rolando Villazon]"),
        new fmrCitation("Ce que tu veux avoir fait avant de mourir, commence le aujourd'hui."),
        new fmrCitation("Je suis un âne, tu es un âne. Où est le problème ? [A.de Mello.]"),
        new fmrCitation("L'amour abstrait de l'humanité est presque toujours de l'égoïsme. [Fiodor Dostoïevski]"),
        new fmrCitation("Moi, je suis content d'être français. D'une part parce que je suis français, et d'autre part parce que j'aime bien être content. [Coluche]"),
        new fmrCitation("La sincérité est trop facile pour que la vérité ne soit pas difficile. [Roger Judrin] "),
        new fmrCitation("Lorsqu'on croit de la foi la plus ferme que l'on possède la vérité, on doit savoir qu'on le croit, non pas croire qu'on le sait. [Jules Lequier]"),
        new fmrCitation("Le doute est un hommage que l'on rend à la vérité. [Ernest Renan]"),
        new fmrCitation("Dieu n'est pas venu supprimer la souffrance. Il n'est même pas venu l'expliquer. Mais il est venu la remplir de sa présence. [Paul Claudel]"),
        new fmrCitation("Croire ou ne pas croire en Dieu relève de la même attitude, l'ignorance."),
        new fmrCitation("Si vous vous contentez de croire en Dieu alors vous ne Le connaîtrez jamais."),
        new fmrCitation("On ne peut connaître Dieu en se contentant de croire en Lui, il faut expérimenter Dieu."),
        new fmrCitation("Libérez-vous de la croyance, devenez un connaissant."),
        new fmrCitation("Croire en Dieu n'est pas une manière pertinente de l'honorer. On se rapproche bien plus de Sa lumière en osant douter de Lui. [M.G. Dantec]"),
        new fmrCitation("La vie est l'ensemble des fonctions qui résistent à la mort. [Xavier Bichat]"),
        new fmrCitation("Vivre, c'est un hasard du temps ; Mourir, c'est une loi de la nature. Je jouis de ce hasard et j'obéis à cette loi. [Lie Tseu]"),
        new fmrCitation("L'hypocondrie est la seule maladie que les hypocondriaques croient qu'ils n'ont pas. [Fred Metcalf]"),
        new fmrCitation("Avant de vous occuper des symptômes de vos patients, occupez-vous de leur vision de la vie. [Dr Bach]"),
        new fmrCitation("Il n'y a pas de plus grand mystère qu'un autre être humain. [Steven Soderbergh]"),
        new fmrCitation("Les mystères sont des objets de contemplation, non des énigmes à élucider. [André Frossard]"),
        new fmrCitation("Pourquoi avons-nous si peur des enfants ? Nous devrions réfléchir un peu plus à la manière dont nous avons peur aussi de nos enfants tout en vivant dans une culture qui prétend toujours les protéger. [Boris Cyrulnik]"),
        new fmrCitation("Les gondoles amarrées, ces chevaux incertains."),
        new fmrCitation("A Venise, les maisons n'ont pour fondation que leur propre reflet. [Michel Tournier]"),
        new fmrCitation("Dieu dort dans le minéral, rêve dans le végétal, s'éveille dans l'animal, pense et aime dans l'homme. [Père Monier]"),
        new fmrCitation("L'argent est le meilleur des serviteurs et le pire des maîtres."),
        new fmrCitation("Chaque pomme est une fleur qui a connu l'amour."),
        new fmrCitation("Le choix de ton ennemi définit ta valeur, si tu affrontes une fourmi tu deviens une fourmi, si tu affrontes un lion tu deviens un lion."),
        new fmrCitation("L'ennemi est bête, il croit que c'est nous l'ennemi alors que c'est lui. [Pierre Desproges]"),
        new fmrCitation("On est en droit de se demander s'il y a une vie avant la mort. [Coluche]"),
        new fmrCitation("Le vrai chef commande à ses hommes mais reçoit ses ordres de Dieu."),
        new fmrCitation("Quand le soleil s'éclipse on en voit la grandeur. [Sénèque]"),
        new fmrCitation("Le savant n'est pas l'homme qui fournit les vraies réponses, c'est celui qui pose les vraies questions. [Claude Lévi-Strauss]"),
        new fmrCitation("Tout vrai chef commence par désobéir aux Dieux.  [extrait du film, 'Himalaya, l'enfance d'un chef']"),
        new fmrCitation("La gloire est le soleil des morts. [Balzac]"),
        new fmrCitation("Et si la réussite consistait à rêver les rêves de notre vie ?"),
        new fmrCitation("L'homme a du génie lorsqu'il rêve. [Akira Kurosawa]"),
        new fmrCitation("La tolérance est un effort de la conscience."),
        new fmrCitation("Le racisme, c'est le naufrage de la conscience."),
        new fmrCitation("La plupart des régimes peuvent se résumer à cette phrase : si c'est bon, crachez. [Fred Metcalf]"),
        new fmrCitation("Il habitait son corps avec une mentalité de locataire...  [La vie est un long fleuve tranquille]"),
        new fmrCitation("Il faut avoir un chaos en soi-même pour accoucher d'une étoile qui danse. [Nietzsche]"),
        new fmrCitation("Ce que nous ignorons a plus d'influence sur nos vies que ce que nous savons. [Maurice G. Dantec]"),
        new fmrCitation("Savez-vous qu'à l'échelle cosmique l'eau est plus rare que l'or."),
        new fmrCitation("Il y a plus de vérité dans l'encre du savant que dans le sang du martyr. [Parole attribuée à Mahomet]"),
        new fmrCitation("L'amour d'une mère remonte des profondeurs de l'océan. [Proverbe russe]"),
        new fmrCitation("Le plus grand voyageur n'est pas celui qui a fait dix fois le tour du monde, mais celui qui a fait une seule fois le tour de lui-même. [Gandhi]"),
        new fmrCitation("Qui se connaît bien, connaît Dieu. [Hazrat Ali]"),
        new fmrCitation("Le plus grand miracle de la médecine, c'est la maladie. [Serment d'Hippocrate]"),
        new fmrCitation("S'aimer soi-même, c'est le début d'une histoire d'amour qui va durer toute la vie. [Oscar Wilde]"),
        new fmrCitation("Le point noir dans la zone blanche nous dit RESTONS HUMBLE, le point blanc dans la zone noire nous dit GARDONS ESPOIR."),
        new fmrCitation("Quand les dieux veulent nous punir, ils exaucent nos prières. [Oscar Wilde]"),
        new fmrCitation("Le meilleur moyen de trouver l'amour est de le donner ; le meilleur moyen de le perdre est de le retenir prisonnier ; et le meilleur moyen de le garder est de lui donner des ailes. [Nancy Sims]"),
        new fmrCitation("There are two major products that came out of Berkeley: LSD and UNIX. We don't believe this to be a coincidence. [Jeremy S. Anderson]"),
        new fmrCitation("Le triomphe des démagogies est passager, mais les ruines sont éternelles. [Charles Péguy]"),
        new fmrCitation("Si le travail c'est l'opium du peuple, alors je ne veux pas finir drogué... [Boris Vian]"),
        new fmrCitation("Le propre de la médiocrité est de se croire supérieur. [François de La Rochefoucauld]"),
        new fmrCitation("Si je dors je dors pour moi ; si je travaille, je ne sais pour qui ce sera. [Johann Wolfgang von Goethe]"),
        new fmrCitation("Les dirigeants ne naissent pas, ils sont fabriqués. [Warren Bennis]")
    };

//******************************************************************************
// fmrCitation()
//******************************************************************************
    private fmrCitation(String cit)
    {
        this.cit = cit;
    }

//******************************************************************************
// get()
//******************************************************************************
    public static String get(long seed)
    {
        Random generator = new Random(seed);
        int rnd = generator.nextInt(citation.length);
        return citation[rnd].cit;
    }
}
