package fr.ozf.fmr;

/**
 * http://www.fruits-legumes.org/
 */
public class fmrFruitsLegumes
{
   private static String[][] Fruits =
      {
         {  // JANVIER
            "Ananas",
            "Avocat",
            "Banane",
            "Citron",
            "Clémentine",
            "Datte",
            "Fruit de la passion",
            "Grenade",
            "Kaki",
            "Kiwi",
            "Litchi",
            "Mandarine",
            "Mangue",
            "Orange",
            "Orange sanguine",
            "Pamplemousse",
            "Papaye",
            "Poire",
            "Pomme"
         },
         {  // FEVRIER
            "Ananas",
            "Avocat",
            "Banane",
            "Citron",
            "Clémentine",
            "Datte",
            "Fruit de la passion",
            "Grenade",
            "Kiwi",
            "Litchi",
            "Mandarine",
            "Mangue",
            "Orange",
            "Orange sanguine",
            "Pamplemousse",
            "Papaye",
            "Pomme"
         },
         {  // MARS
            "Ananas",
            "Avocat",
            "Banane",
            "Citron",
            "Datte",
            "Fruit de la passion",
            "Kiwi",
            "Mandarine",
            "Mangue",
            "Orange sanguine",
            "Pamplemousse",
            "Papaye",
            "Pomme"
         },
         {  // AVRIL
            "Avocat",
            "Banane",
            "Citron",
            "Fruit de la passion",
            "Kiwi",
            "Litchi",
            "Mangue",
            "Papaye",
            "Pomme"
         },
         {  // MAI
            "Avocat",
            "Banane",
            "Citron",
            "Fraise",
            "Fraise des bois",
            "Fruit de la passion",
            "Kiwi",
            "Mangue",
            "Papaye",
            "Tomate",
            "Tomate charnue"
         },
         {  // JUIN
            "Avocat",
            "Banane",
            "Cerise",
            "Citron",
            "Fraise",
            "Fraise des bois",
            "Framboise",
            "Fruit de la passion",
            "Groseille",
            "Groseille à maquereau",
            "Kiwi",
            "Litchi",
            "Mangue",
            "Melon",
            "Nectarine",
            "Papaye",
            "Pastèque",
            "Pêche",
            "Tomate",
            "Tomate charnue",
            "Tomate Peretti"
         },
         {  // JUILLET
            "Abricot",
            "Airelle",
            "Avocat",
            "Banane",
            "Cassis",
            "Cerise",
            "Citron",
            "Fraise",
            "Fraise des bois",
            "Framboise",
            "Fruit de la passion",
            "Groseille",
            "Groseille à maquereau",
            "Kiwi",
            "Litchi",
            "Mangue",
            "Melon",
            "Mûre",
            "Myrtille",
            "Nectarine",
            "Papaye",
            "Pastèque",
            "Pêche",
            "Prune",
            "Quetsche",
            "Tomate",
            "Tomate charnue",
            "Tomate Peretti"
         },
         {  // AOUT
            "Abricot",
            "Airelle",
            "Amande",
            "Avocat",
            "Banane",
            "Cassis",
            "Cerise",
            "Citron",
            "Datte",
            "Figue fraîche",
            "Fraise",
            "Fraise des bois",
            "Framboise",
            "Fruit de la passion",
            "Groseille à maquereau",
            "Kiwi",
            "Litchi",
            "Mangue",
            "Marron",
            "Melon",
            "Mirabelle",
            "Mûre",
            "Myrtille",
            "Nectarine",
            "Noisette",
            "Papaye",
            "Pastèque",
            "Pêche",
            "Poire",
            "Prune",
            "Quetsche",
            "Reine-claude",
            "Tomate",
            "Tomate charnue",
            "Tomate Peretti"
         },
         {  // SEPTEMBRE
            "Amande",
            "Avocat",
            "Banane",
            "Citron",
            "Coing",
            "Datte",
            "Figue fraîche",
            "Framboise",
            "Fruit de la passion",
            "Kiwi",
            "Litchi",
            "Mangue",
            "Marron",
            "Melon",
            "Mirabelle",
            "Mûre",
            "Myrtille",
            "Nectarine",
            "Noisette",
            "Noix",
            "Papaye",
            "Pastèque",
            "Pêche",
            "Poire",
            "Prune",
            "Quetsche",
            "Raisin",
            "Reine-claude",
            "Tomate",
            "Tomate charnue",
            "Tomate Peretti"
         },
         {  // OCTOBRE
            "Avocat",
            "Banane",
            "Citron",
            "Coing",
            "Datte",
            "Figue fraîche",
            "Fruit de la passion",
            "Kaki",
            "Kiwi",
            "Litchi",
            "Mandarine",
            "Mangue",
            "Marron",
            "Noisette",
            "Noix",
            "Papaye",
            "Poire",
            "Pomme",
            "Prune",
            "Quetsche",
            "Raisin"
         },
         {  // NOVEMBRE
            "Ananas",
            "Avocat",
            "Banane",
            "Citron",
            "Clémentine",
            "Datte",
            "Fruit de la passion",
            "Grenade",
            "Kaki",
            "Kiwi",
            "Kumquat",
            "Mandarine",
            "Mangue",
            "Marron",
            "Noix",
            "Orange",
            "Papaye",
            "Poire",
            "Pomme"
         },
         {  // DECEMBRE
            "Ananas",
            "Avocat",
            "Banane",
            "Citron",
            "Clémentine",
            "Datte",
            "Fruit de la passion",
            "Grenade",
            "Kaki",
            "Kiwi",
            "Kumquat",
            "Litchi",
            "Mandarine",
            "Mangue",
            "Marron",
            "Orange",
            "Orange sanguine",
            "Pamplemousse",
            "Papaye",
            "Poire",
            "Pomme"
         }
      };

   private static String[][] Legumes =
      {
         {  // JANVIER
            "Carotte",
            "Céleri",
            "Chou blanc",
            "Chou de Bruxelles",
            "Chou frisé",
            "Chou rouge",
            "Chou-chinois",
            "Citrouille",
            "Endive",
            "Mâche",
            "Oignon",
            "Poireau",
            "Pomme de terre",
            "Salsifis",
            "Topinambour"
         },
         {  // FEVRIER
            "Carotte",
            "Céleri",
            "Chou blanc",
            "Chou frisé",
            "Chou rouge",
            "Chou-chinois",
            "Citrouille",
            "Endive",
            "Mâche",
            "Oignon",
            "Poireau",
            "Pomme de terre",
            "Salsifis",
            "Topinambour"
         },
         {  // MARS
            "Carotte",
            "Céleri",
            "Chou blanc",
            "Chou frisé",
            "Chou rouge",
            "Chou-rave",
            "Endive",
            "Oignon",
            "Petit oignon blanc",
            "Poireau",
            "Salsifis"
         },
         {  // AVRIL
            "Ail",
            "Asperge blanche",
            "Bette",
            "Carotte",
            "Céleri",
            "Chou blanc",
            "Chou rouge",
            "Chou-rave",
            "Epinard",
            "Laitue romaine",
            "Oignon",
            "Petit oignon blanc",
            "Radis"
         },
         {  // MAI
            "Ail",
            "Asperge blanche",
            "Asperge verte",
            "Aubergine",
            "Bette",
            "Betterave rouge",
            "Chou frisé",
            "Chou-chinois",
            "Chou-fleur",
            "Chou-rave",
            "Concombre",
            "Epinard",
            "Fenouil",
            "Laitue romaine",
            "Oignon",
            "Petit oignon blanc",
            "Pomme de terre",
            "Radis",
            "Radis long",
            "Rhubarbe"
         },
         {  // JUIN
            "Ail",
            "Artichaut",
            "Asperge blanche",
            "Asperge verte",
            "Aubergine",
            "Bette",
            "Betterave rouge",
            "Brocoli",
            "Carotte",
            "Céleri branche",
            "Chou blanc",
            "Chou frisé",
            "Chou Romanesco",
            "Chou rouge",
            "Chou-chinois",
            "Chou-fleur",
            "Chou-rave",
            "Concombre",
            "Courgette",
            "Epinard",
            "Fenouil",
            "Haricot",
            "Laitue romaine",
            "Navet",
            "Oignon",
            "Petit oignon blanc",
            "Petit pois",
            "Pois mange-tout",
            "Poivron",
            "Pomme de terre",
            "Radis",
            "Radis long",
            "Rhubarbe"
         },
         {  // JUILLET
            "Ail",
            "Artichaut",
            "Aubergine",
            "Bette",
            "Betterave rouge",
            "Brocoli",
            "Carotte",
            "Céleri",
            "Céleri branche",
            "Chou blanc",
            "Chou frisé",
            "Chou Romanesco",
            "Chou rouge",
            "Chou-chinois",
            "Chou-fleur",
            "Chou-rave",
            "Cima di Rapa",
            "Concombre",
            "Courgette",
            "Epinard",
            "Fenouil",
            "Haricot",
            "Laitue romaine",
            "Maïs",
            "Navet",
            "Oignon",
            "Pâtisson",
            "Petit oignon blanc",
            "Petit pois",
            "Pois mange-tout",
            "Poivron",
            "Pomme de terre",
            "Potiron",
            "Radis",
            "Radis long"
         },
         {  // AOUT
            "Ail",
            "Artichaut",
            "Aubergine",
            "Bette",
            "Betterave rouge",
            "Brocoli",
            "Carotte",
            "Catalonia",
            "Céleri",
            "Céleri branche",
            "Chou blanc",
            "Chou de Bruxelles",
            "Chou frisé",
            "Chou Romanesco",
            "Chou rouge",
            "Chou-chinois",
            "Chou-fleur",
            "Chou-rave",
            "Cima di Rapa",
            "Concombre",
            "Courge",
            "Courgette",
            "Epinard",
            "Fenouil",
            "Haricot",
            "Laitue romaine",
            "Maïs",
            "Navet",
            "Oignon",
            "Pâtisson",
            "Petit oignon blanc",
            "Poivron",
            "Pomme de terre",
            "Potiron",
            "Radis long"
         },
         {  // SEPTEMBRE
            "Artichaut",
            "Aubergine",
            "Bette",
            "Betterave rouge",
            "Brocoli",
            "Carotte",
            "Catalonia",
            "Céleri",
            "Céleri branche",
            "Céleri rave",
            "Chou blanc",
            "Chou de Bruxelles",
            "Chou frisé",
            "Chou Romanesco",
            "Chou rouge",
            "Chou-chinois",
            "Chou-fleur",
            "Chou-rave",
            "Cima di Rapa",
            "Citrouille",
            "Concombre",
            "Courge",
            "Courgette",
            "Epinard",
            "Fenouil",
            "Haricot",
            "Laitue romaine",
            "Maïs",
            "Navet",
            "Oignon",
            "Panais",
            "Pâtisson",
            "Petit oignon blanc",
            "Poireau",
            "Poivron",
            "Pomme de terre",
            "Potiron"
         },
         {  // OCTOBRE
            "Bette",
            "Betterave rouge",
            "Brocoli",
            "Carotte",
            "Catalonia",
            "Céleri",
            "Céleri branche",
            "Céleri rave",
            "Chou blanc",
            "Chou de Bruxelles",
            "Chou frisé",
            "Chou rouge",
            "Chou-chinois",
            "Chou-fleur",
            "Chou-rave",
            "Cima di Rapa",
            "Citrouille",
            "Courge",
            "Epinard",
            "Fenouil",
            "Laitue romaine",
            "Maïs",
            "Oignon",
            "Panais",
            "Petit oignon blanc",
            "Poireau",
            "Poivron",
            "Pomme de terre",
            "Potimarron",
            "Potiron",
            "Salsifis",
            "Topinambour"
         },
         {  // NOVEMBRE
            "Carotte",
            "Catalonia",
            "Céleri",
            "Céleri branche",
            "Chou blanc",
            "Chou de Bruxelles",
            "Chou frisé",
            "Chou rouge",
            "Chou-chinois",
            "Chou-rave",
            "Cima di Rapa",
            "Citrouille",
            "Courge",
            "Endive",
            "Epinard",
            "Fenouil",
            "Mâche",
            "Oignon",
            "Panais",
            "Poireau",
            "Pomme de terre",
            "Potimarron",
            "Salsifis",
            "Topinambour"
         },
         {  // DECEMBRE
            "Carotte",
            "Catalonia",
            "Céleri",
            "Chou blanc",
            "Chou de Bruxelles",
            "Chou frisé",
            "Chou rouge",
            "Chou-chinois",
            "Cima di Rapa",
            "Citrouille",
            "Courge",
            "Endive",
            "Mâche",
            "Oignon",
            "Panais",
            "Poireau",
            "Pomme de terre",
            "Salsifis",
            "Topinambour"
         }
      };

//******************************************************************************
// getFruits()
//******************************************************************************
   public static String[] getFruits(int mois)
   {
      String[] ret = Fruits[mois - 1];
      return ret;
   }

//******************************************************************************
// getLegumes()
//******************************************************************************
   public static String[] getLegumes(int mois)
   {
      String[] ret = Legumes[mois - 1];
      return ret;
   }
}
