package fr.ozf.fmr;

import java.util.ArrayList;
import java.util.List;

public class fmrJourneesMondiales
{
   public static class JourneeMondiale
   {
      public int mois;
      public int jour;
      public String journee;

      public JourneeMondiale(int j, int m, String jrn)
      {
         this.mois = m;
         this.jour = j;
         this.journee = jrn;
      }
   }

   private static JourneeMondiale[] JourneesMondiales =
      {
         new JourneeMondiale(1, 1, "Journée Mondiale de la Paix"),
         new JourneeMondiale(1, 1, "Journée du domaine public"),
         new JourneeMondiale(4, 1, "Journée mondiale du braille"),
         new JourneeMondiale(6, 1, "Journée Mondiale des orphelins de guerre"),
         new JourneeMondiale(9, 1, "Journée mondiale de la Corse"),
         new JourneeMondiale(12, 1, "Kiss a Ginger day, Journée mondiale des roux"),
         new JourneeMondiale(13, 1, "Journée mondiale sans pantalon"),
         new JourneeMondiale(17, 1, "Journée Internationale de la cuisine italienne"),
         new JourneeMondiale(17, 1, "Journée Mondiale du migrant et du réfugié"),
         new JourneeMondiale(18, 1, "Blue monday"),
         new JourneeMondiale(19, 1, "Journée internationale du Pop Corn"),
         new JourneeMondiale(21, 1, "Journée internationale des câlins"),
         new JourneeMondiale(22, 1, "Journée franco-allemande"),
         new JourneeMondiale(24, 1, "Journée Internationale du sport féminin"),
         new JourneeMondiale(26, 1, "Journée Mondiale de la Douane et sur l'éthique"),
         new JourneeMondiale(27, 1, "Journée de la mémoire de l'Holocauste et de la prévention des crimes contre l'humanité"),
         new JourneeMondiale(28, 1, "Journée mondiale de la protection des données"),
         new JourneeMondiale(31, 1, "Journée Mondiale des lépreux"),
         new JourneeMondiale(2, 2, "Journée Mondiale des Zones Humides"),
         new JourneeMondiale(4, 2, "Journée nationale des DIP"),
         new JourneeMondiale(4, 2, "Journée Mondiale contre le cancer"),
         new JourneeMondiale(5, 2, "Journée mondiale du Nutella"),
         new JourneeMondiale(6, 2, "Journée Mondiale sans téléphone mobile"),
         new JourneeMondiale(6, 2, "Journée internationale contre les mutilations génitales"),
         new JourneeMondiale(6, 2, "Journée nationale contre le terrorisme et l'assassinat politique"),
         new JourneeMondiale(8, 2, "Journée internationale de l'épilepsie"),
         new JourneeMondiale(9, 2, "Journée mondiale pour un internet plus sur"),
         new JourneeMondiale(11, 2, "Journée mondiale des malades"),
         new JourneeMondiale(11, 2, "Journée européenne du 112"),
         new JourneeMondiale(12, 2, "Journée Internationale des enfants soldats"),
         new JourneeMondiale(13, 2, "Journée mondiale de la radio"),
         new JourneeMondiale(14, 2, "Journée internationale de sensibilisation aux cardiopathies congénitales"),
         new JourneeMondiale(15, 2, "Journée internationale du cancer de l’enfant"),
         new JourneeMondiale(15, 2, "Journée internationale du Syndrome d'Angelman"),
         new JourneeMondiale(16, 2, "Journée Internationale du patrimoine canadien"),
         new JourneeMondiale(18, 2, "Journée mondiale d'action en faveur du droit de grève"),
         new JourneeMondiale(19, 2, "Journée internationale de la baleine"),
         new JourneeMondiale(20, 2, "Journée mondiale de la justice sociale"),
         new JourneeMondiale(21, 2, "Journée internationale des guides touristiques"),
         new JourneeMondiale(21, 2, "Journée Internationale de la langue maternelle"),
         new JourneeMondiale(22, 2, "Journée Mondiale du Scoutisme"),
         new JourneeMondiale(26, 2, "Journée Mondiale d'action contre l'ordonnance sur les brevets en Inde"),
         new JourneeMondiale(27, 2, "Journée internationale de l'ours polaire"),
         new JourneeMondiale(28, 2, "Journée mondiale sans Facebook"),
         new JourneeMondiale(29, 2, "Journée internationale des maladies rares"),
         new JourneeMondiale(1, 3, "Journée mondiale du compliment"),
         new JourneeMondiale(1, 3, "Journée mondiale de la protection civile"),
         new JourneeMondiale(3, 3, "Journée mondiale de la vie sauvage"),
         new JourneeMondiale(4, 3, "Journée mondiale du tennis"),
         new JourneeMondiale(4, 3, "Journée mondiale de lutte contre l'exploitation sexuelle"),
         new JourneeMondiale(5, 3, "Jour de l'impro"),
         new JourneeMondiale(6, 3, "Journée mondiale de prière"),
         new JourneeMondiale(6, 3, "Journée Internationale de la radio et de la télévision en faveur des enfants"),
         new JourneeMondiale(8, 3, "Journée Mondiale de la Femme"),
         new JourneeMondiale(10, 3, "Journée nationale de l'audition"),
         new JourneeMondiale(10, 3, "Journée Mondiale du rein"),
         new JourneeMondiale(11, 3, "Journée Mondiale de la plomberie"),
         new JourneeMondiale(12, 3, "Semaine internationale de la courtoisie au volant"),
         new JourneeMondiale(12, 3, "Journée mondiale contre la censure sur internet"),
         new JourneeMondiale(13, 3, "Journée mondiale contre l'endométriose"),
         new JourneeMondiale(13, 3, "Journée mondiale de prière pour la Birmanie"),
         new JourneeMondiale(14, 3, "Journée internationale d'action pour les rivières"),
         new JourneeMondiale(14, 3, "Journée mondiale du Pi"),
         new JourneeMondiale(14, 3, "Semaine nationale de lutte contre le cancer"),
         new JourneeMondiale(15, 3, "Journée internationale de lutte contre les violences policières"),
         new JourneeMondiale(15, 3, "Journée Internationale des droits des consommateurs"),
         new JourneeMondiale(17, 3, "Journée mondiale du travail social"),
         new JourneeMondiale(18, 3, "Journée nationale du sommeil"),
         new JourneeMondiale(19, 3, "Journée mondiale d'action contre la guerre (d'occupation en Irak)"),
         new JourneeMondiale(20, 3, "Semaine internationale pour les alternatives aux pesticides"),
         new JourneeMondiale(20, 3, "Journée mondiale du bonheur"),
         new JourneeMondiale(20, 3, "Journée mondiale du moineau"),
         new JourneeMondiale(20, 3, "Journée internationale du macaron"),
         new JourneeMondiale(20, 3, "Journée internationale sans viande"),
         new JourneeMondiale(20, 3, "Journée Internationale de la francophonie"),
         new JourneeMondiale(20, 3, "Journée Mondiale du Conte"),
         new JourneeMondiale(20, 3, "Journée Mondiale de la santé bucco-dentaire"),
         new JourneeMondiale(21, 3, "Journée Mondiale de la Poésie"),
         new JourneeMondiale(21, 3, "Journée(s) internationale(s) du livre voyageur"),
         new JourneeMondiale(21, 3, "Journée Mondiale de la Trisomie 21"),
         new JourneeMondiale(21, 3, "Journée Internationale des forêts"),
         new JourneeMondiale(21, 3, "Journée Internationale pour l'élimination de la discrimination raciale"),
         new JourneeMondiale(21, 3, "Journée mondiale de la marionnette"),
         new JourneeMondiale(21, 3, "Journée européenne de la musique ancienne"),
         new JourneeMondiale(21, 3, "Journée mondiale du rangement de bureaux"),
         new JourneeMondiale(22, 3, "Journée Mondiale de l'eau"),
         new JourneeMondiale(23, 3, "Journée Mondiale de la Météorologie"),
         new JourneeMondiale(24, 3, "Journée Européenne de la glace artisanale"),
         new JourneeMondiale(24, 3, "Journée Mondiale de lutte contre la tuberculose"),
         new JourneeMondiale(25, 3, "Journée de la procrastination"),
         new JourneeMondiale(25, 3, "Tolkien reading day"),
         new JourneeMondiale(25, 3, "Journée Européenne de l'enfant à naître"),
         new JourneeMondiale(27, 3, "Journée nationale du fromage"),
         new JourneeMondiale(27, 3, "Journée Mondiale du théâtre"),
         new JourneeMondiale(29, 3, "Journée mondiale de l'allaitement"),
         new JourneeMondiale(30, 3, "Journée Mondiale des troubles bipolaires"),
         new JourneeMondiale(31, 3, "Journée Internationale de la Visibilité Trans"),
         new JourneeMondiale(31, 3, "Journée mondiale de la sauvegarde des données informatiques"),
         new JourneeMondiale(1, 4, "Journée internationale de la blague"),
         new JourneeMondiale(2, 4, "Journée mondiale de sensibilisation à l'autisme"),
         new JourneeMondiale(2, 4, "Journée mondiale de batailles d'oreillers"),
         new JourneeMondiale(4, 4, "Journée internationale de la sensibilisation au problème des mines et de l'assistance à la lutte antimines"),
         new JourneeMondiale(5, 4, "Journée mondiale du travail invisible"),
         new JourneeMondiale(6, 4, "Journée mondiale du sport pour le développement et la paix"),
         new JourneeMondiale(7, 4, "Journée Mondiale de la santé"),
         new JourneeMondiale(7, 4, "Journée Internationale de réflexion sur le génocide de 1994 au Rwanda"),
         new JourneeMondiale(8, 4, "Journée internationale des Roms"),
         new JourneeMondiale(11, 4, "Journée Mondiale de la maladie de Parkinson"),
         new JourneeMondiale(12, 4, "Journée internationale du vol spatial habité"),
         new JourneeMondiale(15, 4, "Journée Mondiale de l'Art"),
         new JourneeMondiale(16, 4, "Journée Mondiale contre l'esclavage des enfants"),
         new JourneeMondiale(16, 4, "Journée Mondiale du cirque"),
         new JourneeMondiale(16, 4, "Disquaire day"),
         new JourneeMondiale(16, 4, "Journée mondiale de la voix"),
         new JourneeMondiale(17, 4, "Journée Mondiale des luttes paysannes"),
         new JourneeMondiale(17, 4, "Journée Mondiale de l'hémophilie"),
         new JourneeMondiale(17, 4, "Journée Mondiale de prière pour les Vocations"),
         new JourneeMondiale(18, 4, "Journée mondiale des radio amateurs"),
         new JourneeMondiale(18, 4, "Journée internationale des monuments et des sites"),
         new JourneeMondiale(21, 4, "Journée Mondiale des adjointes administratives et secrétaires"),
         new JourneeMondiale(22, 4, "Journée Mondiale de la Terre"),
         new JourneeMondiale(23, 4, "Journée Mondiale du livre et du droit d'auteur"),
         new JourneeMondiale(24, 4, "Journée Mondiale des animaux dans les laboratoires"),
         new JourneeMondiale(24, 4, "Journée Mondiale de la photographie au Sténopé"),
         new JourneeMondiale(24, 4, "Fashion Revolution Day"),
         new JourneeMondiale(25, 4, "Journée Mondiale pour la sauvegarde du lien parental"),
         new JourneeMondiale(25, 4, "Journée Mondiale du paludisme"),
         new JourneeMondiale(26, 4, "Journée Mondiale de la propriété intellectuelle"),
         new JourneeMondiale(28, 4, "Journée Mondiale sur la sécurité et la santé au travail"),
         new JourneeMondiale(29, 4, "Journée Internationale de la danse"),
         new JourneeMondiale(30, 4, "Journée de la non-violence éducative"),
         new JourneeMondiale(30, 4, "Journée Internationale du Jazz"),
         new JourneeMondiale(30, 4, "Journée Mondiale des Mobilités et de l'Accessibilité"),
         new JourneeMondiale(1, 5, "Journée mondiale du travail"),
         new JourneeMondiale(1, 5, "Journée Mondiale du rire"),
         new JourneeMondiale(2, 5, "Journée mondiale du scrapbooking"),
         new JourneeMondiale(3, 5, "Journée du soleil"),
         new JourneeMondiale(3, 5, "Journée Mondiale de la liberté de la presse"),
         new JourneeMondiale(4, 5, "Journée Star wars"),
         new JourneeMondiale(4, 5, "Journée internationale des pompiers"),
         new JourneeMondiale(5, 5, "Journée Mondiale de la Sage-Femme"),
         new JourneeMondiale(5, 5, "Journée Mondiale de l'asthme"),
         new JourneeMondiale(6, 5, "Journée Mondiale du coloriage"),
         new JourneeMondiale(6, 5, "Journée internationale sans régime"),
         new JourneeMondiale(7, 5, "Journée internationale des drones"),
         new JourneeMondiale(7, 5, "Journée Mondiale des orphelins du SIDA"),
         new JourneeMondiale(8, 5, "Journées du souvenir et de la réconciliation en l'honneur des morts de la Seconde Guerre mondiale"),
         new JourneeMondiale(8, 5, "Journée mondiale des communications sociales"),
         new JourneeMondiale(8, 5, "Journée Mondiale de La Croix Rouge"),
         new JourneeMondiale(8, 5, "Jour de l'orgue"),
         new JourneeMondiale(9, 5, "Journée de l'Europe"),
         new JourneeMondiale(10, 5, "Journée commémorative de l'abolition de l'esclavage en France métropolitaine"),
         new JourneeMondiale(10, 5, "Journée mondiale du lupus"),
         new JourneeMondiale(11, 5, "Journée mondiale des éspèces menacées"),
         new JourneeMondiale(12, 5, "Journée Internationale de l'infirmière"),
         new JourneeMondiale(12, 5, "Journée Mondiale de la fibromyalgie"),
         new JourneeMondiale(13, 5, "Journée mondiale de l'ingénierie pour l'avenir"),
         new JourneeMondiale(14, 5, "Journée Mondiale contre l'hypertension"),
         new JourneeMondiale(14, 5, "Journée mondiale du commerce équitable"),
         new JourneeMondiale(15, 5, "Journée Internationale des familles"),
         new JourneeMondiale(17, 5, "Journée Mondiale des Télécommunications"),
         new JourneeMondiale(17, 5, "Journée internationale contre l'homophobie"),
         new JourneeMondiale(18, 5, "Journée mondiale de la maladie coeliaque"),
         new JourneeMondiale(18, 5, "Journée Internationale des musées"),
         new JourneeMondiale(19, 5, "Journée mondiale des MICI"),
         new JourneeMondiale(20, 5, "Journée européenne de la mer"),
         new JourneeMondiale(21, 5, "Journée Mondiale de la diversité culturelle pour le dialogue et le développement"),
         new JourneeMondiale(21, 5, "Journée mondiale des poissons migrateurs"),
         new JourneeMondiale(22, 5, "Journée (nationale) du marin"),
         new JourneeMondiale(22, 5, "Journée Mondiale de la biodiversité"),
         new JourneeMondiale(23, 5, "Journée européenne de l'obésité"),
         new JourneeMondiale(24, 5, "Journée mondiale du bricolage"),
         new JourneeMondiale(25, 5, "Journée internationale des Geek"),
         new JourneeMondiale(25, 5, "Journée Mondiale de l'Afrique"),
         new JourneeMondiale(25, 5, "Journée mondiale de la thyroïde"),
         new JourneeMondiale(25, 5, "Journée Mondiale des enfants disparus"),
         new JourneeMondiale(25, 5, "Journée mondiale de la serviette"),
         new JourneeMondiale(25, 5, "Journée mondiale de la sclérose en plaques"),
         new JourneeMondiale(26, 5, "Journée nationale de dépistage du cancer de la peau"),
         new JourneeMondiale(27, 5, "Journée nationale de la résistance"),
         new JourneeMondiale(28, 5, "Journée Internationale d'action pour la santé des femmes"),
         new JourneeMondiale(29, 5, "Journée Internationale des casques bleus"),
         new JourneeMondiale(30, 5, "Journée mondiale pour le droit aux origines"),
         new JourneeMondiale(31, 5, "Fête mondiale du jeu"),
         new JourneeMondiale(31, 5, "Journée Mondiale sans tabac"),
         new JourneeMondiale(1, 6, "Journée mondiale des parents"),
         new JourneeMondiale(1, 6, "Journée mondiale du lait"),
         new JourneeMondiale(2, 6, "Semaine Nationale de sensibilisation à l'hémochromatose"),
         new JourneeMondiale(2, 6, "Journée Mondiale pour un Tourisme Responsable et Respectueux"),
         new JourneeMondiale(4, 6, "Journée Internationale des enfants victimes innocentes d'agression"),
         new JourneeMondiale(5, 6, "Journée mondiale du naturisme"),
         new JourneeMondiale(5, 6, "Journée Mondiale de l'environnement"),
         new JourneeMondiale(6, 6, "Journée mondiale de la maladie de Verneuil"),
         new JourneeMondiale(6, 6, "Journée mondiale de l'orthoptique"),
         new JourneeMondiale(6, 6, "Journée de la mini-jupe"),
         new JourneeMondiale(8, 6, "Journée Mondiale des océans"),
         new JourneeMondiale(9, 6, "Journée Internationale des Archives"),
         new JourneeMondiale(9, 6, "Journée mondiale de la santé du pied"),
         new JourneeMondiale(10, 6, "journée mondiale de sensibilisation aux passages à niveau"),
         new JourneeMondiale(11, 6, "Journée mondiale du bien-être"),
         new JourneeMondiale(12, 6, "Journée Mondiale contre le travail des enfants"),
         new JourneeMondiale(13, 6, "Journée internationale de sensibilisation à l'albinisme"),
         new JourneeMondiale(14, 6, "Journée Mondiale des donneurs de sang"),
         new JourneeMondiale(15, 6, "Journée Mondiale contre la Faim"),
         new JourneeMondiale(15, 6, "Journée mondiale de lutte contre la maltraitance des personnes âgées"),
         new JourneeMondiale(15, 6, "Journée européenne du vent (de l'énergie éolienne)"),
         new JourneeMondiale(16, 6, "Journée Mondiale de l'enfant Africain"),
         new JourneeMondiale(17, 6, "Journée Mondiale de lutte contre la désertification et la sécheresse"),
         new JourneeMondiale(18, 6, "Journée mondiale du tricot"),
         new JourneeMondiale(19, 6, "journée internationale pour l'élimination de la violence sexuelle en temps de conflit"),
         new JourneeMondiale(19, 6, "Journée Mondiale de la drépanocytose"),
         new JourneeMondiale(20, 6, "Journée Mondiale des réfugiés"),
         new JourneeMondiale(21, 6, "Journée Mondiale du yoga"),
         new JourneeMondiale(21, 6, "Journée internationale de la lenteur"),
         new JourneeMondiale(21, 6, "Journée Mondiale de la Sclérose Latérale Amyotrophique"),
         new JourneeMondiale(22, 6, "Journée nationale de réflexion sur le don d'organes et la greffe"),
         new JourneeMondiale(23, 6, "Journée olympique mondiale"),
         new JourneeMondiale(23, 6, "Journée mondiale des veuves"),
         new JourneeMondiale(23, 6, "Journée mondiale pour la fonction publique"),
         new JourneeMondiale(24, 6, "Journée mondiale anti contrefaçon"),
         new JourneeMondiale(25, 6, "Journée mondiale du vitiligo"),
         new JourneeMondiale(26, 6, "Journée Internationale contre l'abus et le trafic illicite de drogues"),
         new JourneeMondiale(26, 6, "Journée Internationale des Nations Unies pour le soutien aux victimes de la torture"),
         new JourneeMondiale(30, 6, "Journée mondiale des astéroïdes"),
         new JourneeMondiale(1, 7, "Journée mondiale du bandeau blanc contre la pauvreté"),
         new JourneeMondiale(1, 7, "Journée mondiale du reggae"),
         new JourneeMondiale(2, 7, "Journée mondiale des OVNI"),
         new JourneeMondiale(2, 7, "Journée internationale des coopératives"),
         new JourneeMondiale(3, 7, "Journée mondiale sans sacs plastique"),
         new JourneeMondiale(6, 7, "Journée Internationale du baiser"),
         new JourneeMondiale(9, 7, "Journée de la destruction des armes légères"),
         new JourneeMondiale(10, 7, "Journée mondiale des femmes sans voiles"),
         new JourneeMondiale(11, 7, "Journée Mondiale de la population"),
         new JourneeMondiale(17, 7, "Journée mondiale de la justice internationale"),
         new JourneeMondiale(18, 7, "Journée internationale Nelson Mandela"),
         new JourneeMondiale(21, 7, "Journée mondiale de la malbouffe"),
         new JourneeMondiale(26, 7, "Journées mondiales de la jeunesse"),
         new JourneeMondiale(26, 7, "journée internationale pour la conservation de l’écosystème des mangroves"),
         new JourneeMondiale(27, 7, "Journée internationale du fonio"),
         new JourneeMondiale(28, 7, "Journée mondiale contre l'hépatite"),
         new JourneeMondiale(29, 7, "Journée internationale du tigre"),
         new JourneeMondiale(29, 7, "Journée Mondiale des administrateurs système"),
         new JourneeMondiale(30, 7, "Journée mondiale de la dignité des victimes de la traite d’êtres hu,5,ns"),
         new JourneeMondiale(30, 7, "Journée internationale de l'amitié"),
         new JourneeMondiale(31, 7, "Journée internationale de la femme africaine"),
         new JourneeMondiale(1, 8, "Journée internationale de la frite belge"),
         new JourneeMondiale(1, 8, "Semaine Mondiale de l'allaitement maternel"),
         new JourneeMondiale(3, 8, "Journée Mondiale du Capoeiriste"),
         new JourneeMondiale(5, 8, "Journée mondiale de la bière"),
         new JourneeMondiale(7, 8, "Journée Internationale de l'éducation"),
         new JourneeMondiale(8, 8, "Journée internationale du chat"),
         new JourneeMondiale(9, 8, "Journée Internationale des Populations autochtones"),
         new JourneeMondiale(12, 8, "Journée Internationale de la jeunesse"),
         new JourneeMondiale(12, 8, "Journée mondiale des éléphants"),
         new JourneeMondiale(13, 8, "Journée internationale des gauchers"),
         new JourneeMondiale(16, 8, "Journée mondiale du cerf-volant"),
         new JourneeMondiale(17, 8, "Journée internationale du chat noir"),
         new JourneeMondiale(19, 8, "Journée mondiale de l'aide humanitaire"),
         new JourneeMondiale(19, 8, "Journée mondiale de la photographie"),
         new JourneeMondiale(23, 8, "Journée Internationale du souvenir de la traite negrière et de son abolition"),
         new JourneeMondiale(26, 8, "Journée mondiale du chien"),
         new JourneeMondiale(28, 8, "Journée mondiale Topless"),
         new JourneeMondiale(29, 8, "Nuit internationale de la chauve-souris"),
         new JourneeMondiale(29, 8, "Journée Internationale contre les essais nucléaires"),
         new JourneeMondiale(30, 8, "Journée Internationale des personnes disparues"),
         new JourneeMondiale(31, 8, "Journée internationale de prévention des overdoses"),
         new JourneeMondiale(31, 8, "Journée mondiale du blog"),
         new JourneeMondiale(1, 9, "Journée mondiale de prière pour la Création"),
         new JourneeMondiale(3, 9, "Journée mondiale de la barbe"),
         new JourneeMondiale(5, 9, "Journée internationale de sensibilisation aux vautours"),
         new JourneeMondiale(5, 9, "Journée internationale de la charité"),
         new JourneeMondiale(8, 9, "Journée Internationale de l'alphabétisation"),
         new JourneeMondiale(8, 9, "Journée mondiale de la physiothérapie"),
         new JourneeMondiale(9, 9, "Journée mondiale de sensibilisation au syndrome d’alcoolisation fœtale"),
         new JourneeMondiale(10, 9, "Journée Mondiale des premiers secours"),
         new JourneeMondiale(10, 9, "Journée Mondiale de prévention du suicide"),
         new JourneeMondiale(11, 9, "Journée mondiale de lutte contre le terrorisme"),
         new JourneeMondiale(12, 9, "Journée Mondiale des programmeurs et développeurs"),
         new JourneeMondiale(12, 9, "Journée Internationale des Nations-Unies pour la coopération Sud-Sud"),
         new JourneeMondiale(15, 9, "Journée Internationale pour la liberté de l'instruction"),
         new JourneeMondiale(15, 9, "Journée internationale de la démocratie"),
         new JourneeMondiale(15, 9, "Journée mondiale du lymphome"),
         new JourneeMondiale(16, 9, "Journée Internationale de la protection de la couche d'ozone"),
         new JourneeMondiale(17, 9, "Journées européennes du patrimoine"),
         new JourneeMondiale(19, 9, "Journée Européenne de la psychomotricité"),
         new JourneeMondiale(19, 9, "Journée Internationale du Parler Pirate"),
         new JourneeMondiale(19, 9, "Journée nationale de la santé de la peau"),
         new JourneeMondiale(20, 9, "Journée du transport public"),
         new JourneeMondiale(20, 9, "Journée mondiale du logiciel libre"),
         new JourneeMondiale(20, 9, "Journée Européenne de la prostate"),
         new JourneeMondiale(21, 9, "Journée Internationale de la paix"),
         new JourneeMondiale(21, 9, "Journée Mondiale de la maladie d'Alzheimer"),
         new JourneeMondiale(21, 9, "Journée nationale de la qualité de l'air"),
         new JourneeMondiale(21, 9, "Journée internationale de la bibliodiversité"),
         new JourneeMondiale(22, 9, "Journée Mondiale sans voiture"),
         new JourneeMondiale(22, 9, "Journee mondiale de sensibilisation à la leucémie myéloïde chronique"),
         new JourneeMondiale(22, 9, "Journée mondial du rhinocéros"),
         new JourneeMondiale(23, 9, "journée internationale de la maladie de Willis-Ekbom"),
         new JourneeMondiale(23, 9, "Journée de la bisexualité"),
         new JourneeMondiale(23, 9, "Journée nationale du refus de l'échec scolaire"),
         new JourneeMondiale(24, 9, "Journée Mondiale des sourds"),
         new JourneeMondiale(24, 9, "Journée Mondiale contre les brevets logiciels"),
         new JourneeMondiale(25, 9, "Nuit européenne des chercheurs"),
         new JourneeMondiale(26, 9, "Journée Européenne des langues"),
         new JourneeMondiale(26, 9, "Journée mondiale de la contraception"),
         new JourneeMondiale(27, 9, "Journée mondiale du tourisme"),
         new JourneeMondiale(28, 9, "Journée mondiale contre la rage"),
         new JourneeMondiale(28, 9, "Journée mondiale du droit à l'avortement"),
         new JourneeMondiale(28, 9, "Journée Internationale du droit d'accès à l'information"),
         new JourneeMondiale(29, 9, "Journée Mondiale du coeur"),
         new JourneeMondiale(30, 9, "Journée Mondiale de la mer"),
         new JourneeMondiale(30, 9, "Journée mondiale de la traduction"),
         new JourneeMondiale(1, 10, "Journée mondiale de l'urticaire"),
         new JourneeMondiale(1, 10, "Journée mondiale du végétarisme"),
         new JourneeMondiale(1, 10, "Journée Mondiale du chocolat"),
         new JourneeMondiale(1, 10, "Journée Internationale des personnes âgées"),
         new JourneeMondiale(1, 10, "Journée Internationale de la musique"),
         new JourneeMondiale(1, 10, "Journée internationale du café"),
         new JourneeMondiale(2, 10, "Journée Internationale de la non violence"),
         new JourneeMondiale(3, 10, "Journée Mondiale de l'habitat"),
         new JourneeMondiale(3, 10, "Journée mondiale de l'architecture"),
         new JourneeMondiale(4, 10, "Journée Mondiale des animaux"),
         new JourneeMondiale(4, 10, "Journée nationale des aveugles et malvoyants"),
         new JourneeMondiale(5, 10, "Journée Mondiale des enseignantes et des enseignants"),
         new JourneeMondiale(6, 10, "Journée nationale des aidants"),
         new JourneeMondiale(7, 10, "Journée mondiale d'action pour le travail décent"),
         new JourneeMondiale(8, 10, "Journée mondiale des soins palliatifs"),
         new JourneeMondiale(9, 10, "Journée Mondiale de La Poste"),
         new JourneeMondiale(9, 10, "Journée Mondiale du handicap"),
         new JourneeMondiale(10, 10, "Journée Mondiale contre la peine de mort"),
         new JourneeMondiale(10, 10, "Journée Mondiale de la santé mentale"),
         new JourneeMondiale(10, 10, "Journée mondiale de l'oeuf"),
         new JourneeMondiale(10, 10, "Jour de Christophe Colomb"),
         new JourneeMondiale(10, 10, "Journée nationale des DYS"),
         new JourneeMondiale(11, 10, "Journée Internationale des Filles"),
         new JourneeMondiale(11, 10, "Journée Internationale du coming out"),
         new JourneeMondiale(11, 10, "journée française de la maladie d'Huntington"),
         new JourneeMondiale(12, 10, "Journée internationale de solidarité avec les peuples amérindiens"),
         new JourneeMondiale(12, 10, "Journée mondiale pour la vue"),
         new JourneeMondiale(12, 10, "Journée Internationale de la prévention des catastrophes naturelles"),
         new JourneeMondiale(13, 10, "Journée internationale du hamburger"),
         new JourneeMondiale(13, 10, "Journée nationale de la sécurité routière"),
         new JourneeMondiale(14, 10, "Journée Mondiale pour la normalisation"),
         new JourneeMondiale(15, 10, "Journée Internationale de la Canne Blanche"),
         new JourneeMondiale(15, 10, "Journée mondiale de sensibilisation au deuil périnatal."),
         new JourneeMondiale(15, 10, "Journée nationale des toxicomanies"),
         new JourneeMondiale(15, 10, "Journée Internationale de la femme rurale"),
         new JourneeMondiale(15, 10, "Journée Mondiale du lavage des mains"),
         new JourneeMondiale(16, 10, "Journée mondiale de la colonne vertébrale"),
         new JourneeMondiale(16, 10, "Journée Mondiale de l'alimentation"),
         new JourneeMondiale(16, 10, "Journée missionnaire mondiale"),
         new JourneeMondiale(16, 10, "Journée mondiale du pain"),
         new JourneeMondiale(17, 10, "Journée mondiale contre la douleur"),
         new JourneeMondiale(17, 10, "Journée mondiale du don d'organes et de la greffe"),
         new JourneeMondiale(17, 10, "Journée Mondiale du refus de la misère"),
         new JourneeMondiale(18, 10, "Journée Mondiale de la ménopause"),
         new JourneeMondiale(20, 10, "Journée Mondiale de l'ostéoporose"),
         new JourneeMondiale(20, 10, "Journée Internationale des Cuisiniers"),
         new JourneeMondiale(20, 10, "Journée mondiale de la statistique"),
         new JourneeMondiale(20, 10, "Journée Internationale pour la Résolution des Conflits"),
         new JourneeMondiale(20, 10, "Journée internationale du squash"),
         new JourneeMondiale(22, 10, "Journée Mondiale du bégaiement"),
         new JourneeMondiale(24, 10, "Journée Mondiale d'information sur le développement"),
         new JourneeMondiale(24, 10, "Journée des Nations Unies"),
         new JourneeMondiale(24, 10, "Journée mondiale de lutte contre la polio"),
         new JourneeMondiale(25, 10, "Journée Mondiale sans papier"),
         new JourneeMondiale(26, 10, "Journée Mondiale des pâtes"),
         new JourneeMondiale(27, 10, "Journée mondiale de l'ergothérapie"),
         new JourneeMondiale(27, 10, "Journée mondiale du patrimoine audiovisuel"),
         new JourneeMondiale(27, 10, "Journée européenne de la dépression"),
         new JourneeMondiale(28, 10, "Journée Internationale de la langue et de la culture créoles"),
         new JourneeMondiale(28, 10, "Journée mondiale du cinéma d'animation"),
         new JourneeMondiale(28, 10, "Journée mondiale du judo"),
         new JourneeMondiale(29, 10, "Journée mondiale des accidents vasculaires cérébraux"),
         new JourneeMondiale(29, 10, "Journée Mondiale du psoriasis"),
         new JourneeMondiale(30, 10, "Journée mondiale de la Vie"),
         new JourneeMondiale(31, 10, "Journée mondiale de l'épargne"),
         new JourneeMondiale(1, 11, "Journée Mondiale Vegan"),
         new JourneeMondiale(2, 11, "Journée internationale de la fin de l’impunité pour les crimes commis contre des journalistes"),
         new JourneeMondiale(5, 11, "Journée nationale de lutte contre le harcèlement scolaire"),
         new JourneeMondiale(5, 11, "Journée annuelle des parents au bureau"),
         new JourneeMondiale(6, 11, "Journée Internationale pour la préservation de l'environnement en temps de guerre"),
         new JourneeMondiale(7, 11, "Journée Internationale de l'écrivain africain"),
         new JourneeMondiale(8, 11, "Journée internationale de la radiologie"),
         new JourneeMondiale(9, 11, "Journée mondiale de la qualité"),
         new JourneeMondiale(10, 11, "Journée internationale des stagiaires"),
         new JourneeMondiale(10, 11, "Journée mondiale de sensibilisation aux tumeurs neuro-endocrines"),
         new JourneeMondiale(10, 11, "Journée Mondiale de la science au service de la paix et du développement"),
         new JourneeMondiale(12, 11, "Journée Mondiale de la pneumonie"),
         new JourneeMondiale(13, 11, "Journée mondiale de l'utilisabilité"),
         new JourneeMondiale(13, 11, "Journée Mondiale de la gentillesse"),
         new JourneeMondiale(13, 11, "Journée mondiale de la vasectomie"),
         new JourneeMondiale(14, 11, "Journée mondiale du diabète"),
         new JourneeMondiale(14, 11, "Semaine mondiale de l'entrepreneur"),
         new JourneeMondiale(15, 11, "Journée mondiale des écrivains en prison"),
         new JourneeMondiale(15, 11, "Journée nationale de la trisomie 21"),
         new JourneeMondiale(15, 11, "Journée mondiale du recyclage"),
         new JourneeMondiale(16, 11, "Journée Internationale de la tolérance"),
         new JourneeMondiale(17, 11, "Journée de la Philosophie à l'UNESCO"),
         new JourneeMondiale(17, 11, "Journée Nationale pour l'épilepsie"),
         new JourneeMondiale(17, 11, "Journée Mondiale de la Prématurité"),
         new JourneeMondiale(18, 11, "Journée internationale des GIS (systèmes d'information géographiques)"),
         new JourneeMondiale(18, 11, "Journée mondiale contre les Broncho-Pneumopathies Chroniques Obstructives"),
         new JourneeMondiale(18, 11, "Journée européenne d'information sur les antibiotiques"),
         new JourneeMondiale(19, 11, "Journée nationale des assistantes maternelles"),
         new JourneeMondiale(19, 11, "Journée internationale de l'homme"),
         new JourneeMondiale(19, 11, "Semaine européenne de réduction des déchets"),
         new JourneeMondiale(19, 11, "Journée mondiale pour la prévention des abus envers les enfants"),
         new JourneeMondiale(19, 11, "Journée Mondiale des toilettes"),
         new JourneeMondiale(20, 11, "Journée nationale contre l'herpés"),
         new JourneeMondiale(20, 11, "Journée Mondiale pour l'industrialisation de l'Afrique"),
         new JourneeMondiale(20, 11, "Journée Internationale des droits de l'enfant"),
         new JourneeMondiale(20, 11, "Journée internationale du souvenir trans"),
         new JourneeMondiale(20, 11, "Journée mondiale du souvenir des victimes des accidents de la route"),
         new JourneeMondiale(21, 11, "Journée mondiale du jeu vidéo"),
         new JourneeMondiale(21, 11, "Journée Mondiale des pecheurs artisans et des travailleurs de la mer"),
         new JourneeMondiale(21, 11, "Journée Mondiale de la Télévision"),
         new JourneeMondiale(24, 11, "Journée internationale de la Bible"),
         new JourneeMondiale(25, 11, "Journée mondiale anti foie gras"),
         new JourneeMondiale(25, 11, "Journée Internationale pour l'élimination de la violence à l'égard des femmes"),
         new JourneeMondiale(26, 11, "Journée Mondiale de l'égalité des chances"),
         new JourneeMondiale(26, 11, "Journée Mondiale Sans Achats"),
         new JourneeMondiale(26, 11, "Journée des enfants des rues"),
         new JourneeMondiale(26, 11, "Journée internationale des aides-soignants"),
         new JourneeMondiale(29, 11, "Journée Internationale de solidarité avec le peuple palestinien"),
         new JourneeMondiale(1, 12, "Journée Mondiale de la lutte contre le SIDA"),
         new JourneeMondiale(2, 12, "Journée Internationale pour l'abolition de l'esclavage"),
         new JourneeMondiale(3, 12, "Journée nationale du cinéma indépendant"),
         new JourneeMondiale(3, 12, "Journée Internationale des personnes handicapées"),
         new JourneeMondiale(5, 12, "Journée Internationale du Ninja"),
         new JourneeMondiale(5, 12, "Journée mondiale du bénévolat"),
         new JourneeMondiale(5, 12, "Journée mondiale des sols"),
         new JourneeMondiale(7, 12, "Journée Internationale de l'aviation civile"),
         new JourneeMondiale(8, 12, "Journée Mondiale du Climat"),
         new JourneeMondiale(9, 12, "Journée Mondiale des Nations Unies contre la corruption"),
         new JourneeMondiale(9, 12, "Journée nationale de la laïcité"),
         new JourneeMondiale(10, 12, "Journée Mondiale des droits de l'homme"),
         new JourneeMondiale(10, 12, "Journée internationale pour les droits des animaux"),
         new JourneeMondiale(11, 12, "Journée mondiale des enfants partis trop tôt"),
         new JourneeMondiale(11, 12, "Journée Internationale de la montagne"),
         new JourneeMondiale(11, 12, "Journée mondiale du chant choral"),
         new JourneeMondiale(12, 12, "Journée internationale du pull de Noël"),
         new JourneeMondiale(15, 12, "Journée mondiale des Otakus"),
         new JourneeMondiale(15, 12, "Journée internationale du thé"),
         new JourneeMondiale(15, 12, "Journée [universelle] de l'esperanto"),
         new JourneeMondiale(18, 12, "Journée mondiale pour la langue Arabe"),
         new JourneeMondiale(18, 12, "Journée internationale des migrants"),
         new JourneeMondiale(20, 12, "Journée Internationale de La Solidarité Humaine"),
         new JourneeMondiale(20, 12, "Journée mondiale de l'humanisme"),
         new JourneeMondiale(21, 12, "Journée Mondiale de l'Orgasme"),
         new JourneeMondiale(31, 12, "Journée mondiale vous souhaite une bonne année")
      };

   public static List<String> getJournee(int m, int j)
   {
      List<String> rc = new ArrayList<String>();
      for (JourneeMondiale n : JourneesMondiales)
      {
         if (n.mois == m && n.jour == j)
         {
            rc.add(n.journee);
         }
      }
      return rc;
   }
}
